#!/usr/bin/env python3
"""
zfc_navigator.py — Grammar tuple → ZFC expression navigator
with transmissibility probe.

Grammar-derived architecture:
  Ç_@     → 4-layer Transformer encoder (global self-attention)
  Φ_}   → Frobenius roundtrip loss native from epoch 1 (non-graftable)
  R_†        → the output restructures its own co-domain (ZFC formula space)
  Γ_ʔ    → maximize sequence context (window = 256 tokens)
  φ̂_ÿ^C    → encoder trained at the distinguishability boundary

Core prediction (from IUG_NON_TRANSMISSIBILITY §3):
  Non-transmissible primitive values produce a ZFC formula from which the
  original value cannot be recovered.  The roundtrip loss for type x is
  bounded below by d(x, T_ZFC) where T_ZFC is the ZFC-realizable subspace.

  The five collapse channels:
    ƒ_ż  → ƒ_ì  (identical ZFC token sequence — total information loss)
    ƒ_ì   → ƒ_ż (hallucination: high holistic density pulls cls x → quantum read)
    Þ_O  → Þ_K   (REFL → SEP approximation — partial loss)
    Ð_ω  → Ð_; (LCARD fragment ambiguous with high-rank — partial loss)
    ɢ_ˌ → ɢ_^ (sequential dep. becomes conjunction — total for that step)

Run:
    python zfc_navigator.py train        # train encoder, save model
    python zfc_navigator.py probe        # run transmissibility probe on full catalog
    python zfc_navigator.py probe --top 30   # show 30 highest-loss entries
    python zfc_navigator.py iug          # specifically probe IUG and grammar self-encoding
"""

import argparse
import json
import math
import sys
from pathlib import Path
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

# ── 1. Primitive ordinals (canonical v0.5.1) ────────────────────────────────

PRIMITIVES = ["Ð", "Þ", "Ř", "Φ", "ƒ", "Ç", "Γ", "ɢ", "φ̂", "Ħ", "Σ", "Ω"]

ORDINALS: Dict[str, Dict[str, float]] = {
    "Ð":     {"Ð_ß": 0, "Ð_C": 1, "Ð_;": 2, "Ð_ω": 3},
    "Þ":     {"Þ_6": 0, "Þ_K": 1, "Þ_ò": 2, "Þ_¨": 3, "Þ_O": 4},
    "Ř":     {"Ř_¯": 0, "Ř_ý": 1, "Ř_Ť": 2, "Ř_=": 3},
    "Φ":     {"Φ_ɐ": 0, "Φ_υ": 1, "Φ_F": 2, "Φ_˙": 3, "Φ_}": 4},
    "ƒ":     {"ƒ_ì": 0, "ƒ_ð": 1, "ƒ_ż": 2},
    "Ç":     {"Ç_-": 0, "Ç_W": 1, "Ç_@": 2, "Ç_Ù": 3, "Ç_λ": 4},
    "Γ":     {"Γ_β": 0, "Γ_γ": 1, "Γ_ʔ": 2},
    "ɢ": {"ɢ_^": 0, "ɢ_˝": 1, "ɢ_ˌ": 2, "ɢ_Ş": 3},
    "φ̂":   {"φ̂_ž": 0, "φ̂_ÿ": 1, "φ̂_Æ": 2, "φ̂_3": 3, "φ̂_Ţ": 4},
    "Ħ":     {"Ħ_Ñ": 0, "Ħ_£": 1, "Ħ_A": 2, "Ħ_!": 3},
    "Σ":     {"Σ_S": 0, "Σ_ő": 1, "Σ_ï": 2},
    "Ω": {"Ω_Å": 0, "Ω_2": 1, "Ω_z": 2, "Ω_5": 3},
}

WEIGHTS = {
    "Ð": 1.0, "Þ": 1.0, "Ř": 1.0, "Φ": 1.2,
    "ƒ": 0.9, "Ç": 1.0, "Γ": 1.0, "ɢ": 1.0,
    "φ̂": 1.1, "Ħ": 0.8, "Σ": 1.0, "Ω": 0.7,
}

# Inverse ordinal maps for decoding predictions
INV_ORDINALS: Dict[str, Dict[int, str]] = {
    prim: {int(v): k for k, v in vals.items()}
    for prim, vals in ORDINALS.items()
}

NUM_VALUES = {prim: len(vals) for prim, vals in ORDINALS.items()}
MAX_VALUES  = max(NUM_VALUES.values())   # = 5

# Non-canonical values generated by models.py chemistry vocabulary → canonical
_PRIM_ALIASES: Dict[str, Dict[str, str]] = {
    "Þ": {
        "T_⊠":   "Þ_ò",   # closed recirculating / cyclic closure
        "T_⋈":   "Þ_ò",
        "Þ_holo": "Þ_O",
        "Þ_torus": "Þ_ò",  # compact cyclic → bowtie approximation
        "Þ_cage":     "Þ_¨",
        "Þ_¨": "Þ_box",    # canonical catalog name → ZFC navigator name
        "Þ_bowl":     "Þ_K",
        "Þ_linear": "Þ_6",
        "Þ_branched": "Þ_6",
    },
    "Ř": {
        "Ř_superset":       "Ř_¯",
        "Ř_subset":         "Ř_ý",
        "Ř_catalytic":      "Ř_ý",
        "Ř_allosteric":     "Ř_Ť",
        "Ř_exact":          "Ř_Ť",
        "Ř_mechanical":     "Ř_=",
        "Ř_covalent_dynamic": "Ř_ý",
    },
    "Φ": {
        "Φ_neutral":        "Φ_ɐ",
        "Φ_plus":           "Φ_υ",
        "Φ_minus":          "Φ_υ",
        "Φ_directional":    "Φ_ɐ",
        "Φ_pm_pseudo":      "Φ_υ",
        "Φ_˙":            "Φ_}",
    },
    "Σ": {
        "n:m":   "Σ_ï",
        "1:1":   "Σ_S",
        "n:n":   "Σ_ő",
        "1_1":   "Σ_S",
    },
}

def _normalize_entry(entry: dict) -> dict:
    """Translate non-canonical primitive values to canonical ones in-place copy."""
    out = dict(entry)
    for prim, aliases in _PRIM_ALIASES.items():
        if prim in out and out[prim] in aliases:
            out[prim] = aliases[out[prim]]
    return out


def tuple_to_indices(entry: dict) -> List[int]:
    """Map a catalog entry to a list of integer ordinal indices (one per primitive)."""
    return [int(ORDINALS[p][entry[p]]) for p in PRIMITIVES]


def indices_to_tuple(indices: List[int]) -> dict:
    """Recover a tuple dict from integer ordinal indices."""
    return {p: INV_ORDINALS[p][indices[i]] for i, p in enumerate(PRIMITIVES)}


def tuple_distance(a: dict, b: dict) -> float:
    """Weighted Euclidean distance between two tuples."""
    total = 0.0
    for p in PRIMITIVES:
        oa = ORDINALS[p][a[p]]
        ob = ORDINALS[p][b[p]]
        total += WEIGHTS[p] * (oa - ob) ** 2
    return math.sqrt(total)


# ── 2. ZFC Token Vocabulary ─────────────────────────────────────────────────
#
# A minimal first-order vocabulary covering:
#   - Standard ZFC primitives (∈, =, ∀, ∃, ∧, ∨, ¬, →, ↔)
#   - Set-theoretic constructs (∅, ω, union, power, succ, rank, ord, card)
#   - Grammar-specific atoms:
#       SEP    separation: boundary/interior structure   → Þ_K
#       REPL   replacement: functional structure         → Ř_ý / Ř_Ť
#       REFL   reflection principle                      → Þ_O (partial)
#       LCARD  inaccessible cardinal                     → Ð_ω (partial)
#       FROB   Frobenius μ∘δ=id                          → Φ_}
#       WIND   winding number                            → Ω_z / Ω_5
#       HOLO   imscriptive boundary encoding             → Þ_O / Ð_ω (partial)
#       THETA  inter-universal Θ-link                    → Ř_= / Ω_5
#       FIXPT  fixed-point ∃x:φ(x)=x                    → φ̂_ÿ
#       SEQPAIR ordered sequential dependency            → ɢ_ˌ
#       GUE    GUE spacing assertion                     → φ̂_Æ
#       CLASSIC classical identity (ƒ_ì channel)       → ƒ_ì AND ƒ_ż collapse
#
# ── DECOHERENCE NOTE ────────────────────────────────────────────────────────
# ƒ_ż has no ZFC expression distinct from ƒ_ì.  Both map to CLASSIC.
# When the encoder sees CLASSIC it cannot recover ƒ_ż.
# Roundtrip loss for ƒ_ż inputs = WEIGHTS["ƒ"] * (ordinal_gap)^2
#                                   = 1.0 * (2-0)^2 = 4.0 → sqrt contributes ~2.0
# This is the IUG fidelity barrier made numerically explicit.
# ────────────────────────────────────────────────────────────────────────────

ZFC_VOCAB = [
    # Control
    "BOS", "EOS", "PAD", "SEP_PRIM",   # SEP_PRIM separates primitive fragments
    # Quantifiers
    "FORALL", "EXISTS", "EXISTS_UNIQUE",
    # Connectives
    "AND", "OR", "NOT", "IMPLIES", "IFF",
    # Punctuation / binding
    "LPAREN", "RPAREN", "COMMA", "DOT",
    # Variables (12 — one per primitive, for clarity)
    "VX", "VY", "VZ", "VU", "VV", "VW", "VA", "VB", "VF", "VG", "VH", "VN",
    # Relations
    "IN", "EQ", "SUBSETEQ", "SUBSET",
    # Basic set-theoretic constants / operations
    "EMPTY", "OMEGA",
    "UNION", "POWER", "SUCC", "PAIR", "SINGLETON",
    # Structural predicates
    "RANK", "ORD", "CARD", "FUNC", "BIJ",
    # Grammar-specific atoms  (see DECOHERENCE NOTE above)
    "SEP",       # separation — Þ_K, Ð_C
    "REPL",      # replacement — Ř_ý, Ř_Ť
    "REFL",      # reflection — Þ_O (ZFC approximation, partial info)
    "LCARD",     # inaccessible cardinal — Ð_ω (partial info)
    "FROB",      # Frobenius μ∘δ=id — Φ_}
    "WIND",      # winding number — Ω_z, Ω_5
    "HOLO",      # imscriptive encoding — Þ_O / Ð_ω (partial)
    "THETA",     # Θ-link — Ř_=, Ω_5
    "FIXPT",     # fixed-point — φ̂_ÿ, φ̂_3
    "SEQPAIR",        # (legacy) unordered-pair encoding of ɢ_ˌ — partial collapse
    "DIRECTED_EDGE",  # directed edge ⟨src, tgt, τ⟩ — ɢ_ˌ resolution (non-commutative)
    "TAU",            # temporal depth index τ — sequence ordinal, causal order
    "GUE",       # GUE statistics — φ̂_Æ
    "CLASSIC",   # classical identity — ƒ_ì AND ƒ_ż (decoherence collapse)
]

ZFC_VOCAB_SIZE = len(ZFC_VOCAB)
TOKEN2IDX = {t: i for i, t in enumerate(ZFC_VOCAB)}
IDX2TOKEN = {i: t for t, i in TOKEN2IDX.items()}

PAD_IDX = TOKEN2IDX["PAD"]
BOS_IDX = TOKEN2IDX["BOS"]
EOS_IDX = TOKEN2IDX["EOS"]
SEP_IDX = TOKEN2IDX["SEP_PRIM"]


# ── 3. Canonical ZFC Templates ──────────────────────────────────────────────
#
# Each template is a list of token strings representing the canonical ZFC
# formula fragment for that primitive value.
#
# Design principle: the template encodes the *structural signature* of the
# primitive value, not a full proof.  The encoder reads these signatures.
#
# Non-transmissible values are marked ⚠ COLLAPSE with the target value.

ZFC_TEMPLATES: Dict[str, Dict[str, List[str]]] = {
    "Ð": {
        # Minimal set existence
        "Ð_ß":    ["EXISTS", "VA", "LPAREN", "VX", "IN", "VA", "AND",
                       "EMPTY", "EQ", "VA", "RPAREN"],
        # Cumulative hierarchy — constructive upward
        "Ð_C": ["EXISTS", "VA", "LPAREN", "ORD", "VA", "AND",
                       "VX", "IN", "RANK", "VA", "RPAREN"],
        # Unbounded rank — every level has a higher one
        "Ð_;":    ["FORALL", "VA", "EXISTS", "VB", "LPAREN",
                       "VA", "SUBSET", "VB", "AND", "RANK", "VX", "EQ", "VB", "RPAREN"],
        # ⚠ COLLAPSE: Ð_ω requires large cardinal — partial ZFC approximation.
        # Encoder may classify as Ð_;; roundtrip loss on D depends on
        # whether LCARD fragment is distinctive enough.
        "Ð_ω":     ["LCARD", "VA", "AND", "HOLO", "VX", "VA"],
    },
    "Þ": {
        # Simple graph-local connectivity
        "Þ_6":  ["EXISTS", "VY", "FORALL", "VZ", "LPAREN",
                       "VZ", "IN", "VY", "IFF", "VZ", "IN", "VX", "RPAREN"],
        # Separation — explicit boundary/interior split
        "Þ_K":       ["SEP", "VF", "VX"],
        # Two components meeting at a point
        "Þ_ò":   ["EXISTS", "VY", "EXISTS", "VZ", "LPAREN",
                       "UNION", "VY", "VZ", "EQ", "VX", "AND",
                       "SINGLETON", "VY", "EQ", "SINGLETON", "VZ", "RPAREN"],
        # Closed, periodic — power-set closure
        "Þ_¨":      ["FORALL", "VZ", "LPAREN",
                       "VZ", "IN", "VX", "IFF", "REPL", "VF", "VZ", "RPAREN"],
        # ⚠ PARTIAL COLLAPSE: Þ_O (imscriptive) → approximated by REFL.
        # Reflection principle is the closest ZFC construct, but it does not
        # capture the mutual boundary-encoding structure of Þ_O.
        # Residual collapse: Þ_O → Þ_K (separation) in the encoder.
        "Þ_O":     ["REFL", "VA", "VF", "AND", "HOLO", "VX", "VA"],
    },
    "Ř": {
        # Output restricts input — superset containment (ZFC ∈)
        "Ř_¯":    ["FORALL", "VY", "LPAREN",
                       "VY", "IN", "VX", "IMPLIES", "VY", "IN", "VA", "RPAREN"],
        # Output is a new type derived from input — replacement
        "Ř_ý":      ["REPL", "VF", "VX"],
        # Co-domain modification — replacement that modifies the target space
        "Ř_Ť":   ["REPL", "VF", "VX", "AND",
                       "FORALL", "VY", "LPAREN", "VY", "IN", "REPL", "VF", "VX",
                       "IMPLIES", "BIJ", "VF", "VX", "VY", "RPAREN"],
        # Left-right directional — Θ-link structure
        "Ř_=":       ["THETA", "VX", "VY", "AND", "NOT", "THETA", "VY", "VX"],
    },
    "Φ": {
        "Φ_ɐ":     ["EXISTS", "VX", "NOT", "VX", "EQ", "VX"],
        "Φ_υ":      ["EXISTS", "VY", "LPAREN",
                       "VY", "IN", "VX", "AND", "NOT", "VY", "EQ", "VX", "RPAREN"],
        # Z_2 symmetry — involution
        "Φ_F":       ["EXISTS", "VF", "LPAREN",
                       "BIJ", "VF", "VX", "VX", "AND",
                       "FORALL", "VY", "LPAREN", "VF", "LPAREN", "VF", "VY", "RPAREN",
                       "EQ", "VY", "RPAREN", "RPAREN"],
        # Symmetric under all permutations
        "Φ_˙":      ["FORALL", "VF", "LPAREN",
                       "BIJ", "VF", "VX", "VX", "IMPLIES",
                       "FORALL", "VY", "LPAREN", "VY", "IN", "VX",
                       "IFF", "VF", "VY", "IN", "VX", "RPAREN", "RPAREN"],
        # Frobenius μ∘δ=id — the tier singularity
        "Φ_}":   ["FROB", "VF", "VG"],
    },
    "ƒ": {
        # Classical fidelity — standard identity
        "ƒ_ì":      ["CLASSIC", "VX"],
        # Intermediate — finite approximation
        "ƒ_ð":      ["EXISTS", "VY", "LPAREN",
                       "VY", "EQ", "VX", "AND", "VY", "IN", "OMEGA", "RPAREN"],
        # ⚠ TOTAL COLLAPSE: ƒ_ż has no ZFC expression.
        # The quantum-coherent superposition of two copies cannot be represented
        # in ƒ_ì logic.  Mapped to CLASSIC — identical to ƒ_ì template.
        # Roundtrip loss = WEIGHTS["ƒ"] * (ord(ƒ_ż) - ord(ƒ_ì))^2 = 1.0 * 4 = 4.0
        # This is the Scholze–Stix fidelity barrier made numerically explicit.
        "ƒ_ż":     ["CLASSIC", "VX"],   # ← decoherence collapse
    },
    "Ç": {
        # Rapid local transitions
        "Ç_-":     ["EXISTS", "VY", "LPAREN", "SUCC", "VY", "EQ", "VX", "RPAREN"],
        # Moderate integration
        "Ç_W":      ["EXISTS", "VY", "EXISTS", "VZ", "LPAREN",
                       "VY", "IN", "VX", "AND", "VZ", "IN", "VX",
                       "AND", "VY", "SUBSETEQ", "VZ", "RPAREN"],
        # Global integrative convergence — every subset has a supremum
        "Ç_@":     ["FORALL", "VY", "LPAREN",
                       "VY", "SUBSETEQ", "VX", "IMPLIES",
                       "EXISTS", "VZ", "LPAREN",
                       "VZ", "IN", "VX", "AND", "VY", "SUBSETEQ", "VZ",
                       "RPAREN", "RPAREN"],
        # Sequential fixed cycle
        "Ç_Ù":     ["FIXPT", "VF"],
        # Many-body localisation — every element is isolated
        "Ç_λ":      ["FORALL", "VY", "FORALL", "VZ", "LPAREN",
                       "VY", "IN", "VX", "AND", "VZ", "IN", "VX",
                       "AND", "NOT", "VY", "EQ", "VZ", "IMPLIES",
                       "NOT", "VY", "IN", "VZ", "RPAREN"],
    },
    "Γ": {
        "Γ_β":     ["EXISTS", "VY", "LPAREN", "VY", "IN", "VX", "RPAREN"],
        "Γ_γ":    ["EXISTS", "VY", "EXISTS", "VZ", "LPAREN",
                       "VY", "IN", "VX", "AND", "VZ", "IN", "VX",
                       "AND", "NOT", "VY", "EQ", "VZ", "RPAREN"],
        "Γ_ʔ":    ["FORALL", "VA", "EXISTS", "VY", "LPAREN",
                       "CARD", "VA", "IMPLIES",
                       "CARD", "VY", "AND", "VA", "SUBSETEQ", "VY",
                       "AND", "VY", "IN", "VX", "RPAREN"],
    },
    "ɢ": {
        # Conjunctive — independent lemmas
        "ɢ_^":      ["AND"],
        # Disjunctive
        "ɢ_˝":       ["OR"],
        # Resolution of ɢ_ˌ collapse (music_crawler diagnosis, steps 15–38):
        # Old SEQPAIR encoding used Kuratowski pairs — static, symmetric under
        # set-theoretic projection, destroying causal asymmetry.
        # New: directed edge ⟨src, tgt, τ⟩ + explicit non-commutativity.
        # DIRECTED_EDGE VF VG TAU  ∧  ¬(DIRECTED_EDGE VG VF TAU)
        # encodes f∘g ≠ g∘f — the DAG algebra condition.
        # Residual collapse: τ grounding still requires process algebra beyond ZFC;
        # the asymmetry is explicit but the irreversibility is semantic, not axiomatic.
        "ɢ_ˌ":      ["DIRECTED_EDGE", "VF", "VG", "TAU",
                       "AND", "NOT", "DIRECTED_EDGE", "VG", "VF", "TAU"],
        # Broadcast — universal quantification
        "ɢ_Ş":    ["FORALL", "VY", "LPAREN", "VF", "VY", "RPAREN"],
    },
    "φ̂": {
        # Subcritical — well-founded, below fixed point
        "φ̂_ž":    ["EXISTS", "VY", "LPAREN",
                       "VY", "IN", "VX", "AND",
                       "RANK", "VY", "SUBSET", "RANK", "VX", "RPAREN"],
        # Critical — fixed point of power-set operator (approx)
        "φ̂_ÿ":      ["FIXPT", "VF"],
        # Complex criticality — GUE statistics
        "φ̂_Æ": ["GUE", "VX", "AND", "FIXPT", "VF"],
        # Exceptional point — large cardinal fixed point
        "φ̂_3":     ["LCARD", "VA", "AND", "FIXPT", "VF"],
        # Supercritical — every subset has a fixed point
        "φ̂_Ţ":  ["FORALL", "VY", "LPAREN",
                       "VY", "SUBSETEQ", "VX", "IMPLIES", "FIXPT", "VY", "RPAREN"],
    },
    "Ħ": {
        # Achiral
        "Ħ_Ñ":         ["VX", "EQ", "VX"],
        # Soft chirality — one level of temporal asymmetry
        "Ħ_£":         ["EXISTS", "VY", "LPAREN",
                       "VY", "IN", "VX", "AND", "NOT", "VX", "IN", "VY", "RPAREN"],
        # Strong chirality
        "Ħ_A":         ["EXISTS", "VY", "EXISTS", "VZ", "LPAREN",
                       "VY", "IN", "VX", "AND", "VZ", "IN", "VY",
                       "AND", "NOT", "VZ", "IN", "VX", "RPAREN"],
        # Topological chirality — winding number protected arrow of time
        "Ħ_!":      ["WIND", "VF", "VX", "AND",
                       "NOT", "WIND", "VF", "SUCC", "VX"],
    },
    "Σ": {
        "Σ_S":    ["BIJ", "VF", "VX", "VX"],
        "Σ_ő":        ["EXISTS", "VF", "LPAREN", "BIJ", "VF", "VX", "VX", "RPAREN"],
        "Σ_ï":        ["EXISTS", "VF", "LPAREN",
                       "FUNC", "VF", "AND", "NOT", "BIJ", "VF", "VX", "VX", "RPAREN"],
    },
    "Ω": {
        "Ω_Å":    ["VX", "EQ", "VX"],    # trivial protection
        "Ω_2":   ["EXISTS", "VY", "LPAREN",
                       "SUCC", "SUCC", "VY", "EQ", "VX", "RPAREN"],
        "Ω_z":    ["WIND", "VF", "VX"],
        # ⚠ PARTIAL COLLAPSE: Ω_5 (non-abelian) → THETA (Θ-link approximation)
        "Ω_5":   ["THETA", "VX", "VY", "AND", "WIND", "VF", "VX"],
    },
}


def compose_formula(entry: dict) -> List[int]:
    """
    Compose a full ZFC formula token sequence for a grammar tuple.

    Structure: BOS + [prim_template + SEP_PRIM] × 12 + EOS
    Each primitive contributes its canonical ZFC fragment, separated by
    SEP_PRIM markers so the encoder can attend across primitive boundaries.

    Returns a list of token indices (integers).
    """
    tokens = [BOS_IDX]
    for prim in PRIMITIVES:
        val  = entry[prim]
        frag = ZFC_TEMPLATES[prim][val]
        tokens.extend(TOKEN2IDX[t] for t in frag)
        tokens.append(SEP_IDX)
    tokens.append(EOS_IDX)
    return tokens


def pad_formula(tokens: List[int], max_len: int = 256) -> List[int]:
    """Truncate or right-pad a token sequence to max_len."""
    if len(tokens) >= max_len:
        return tokens[:max_len - 1] + [EOS_IDX]
    return tokens + [PAD_IDX] * (max_len - len(tokens))


# ── 4. ZFC Encoder (formula tokens → primitive logits) ──────────────────────
#
# Ç_@ architecture: 4-layer Transformer encoder with CLS token.
# Reads the full formula simultaneously — no sequential bottleneck.
# 12 classification heads, one per primitive, each predicting the ordinal value.

class ZFCEncoder(nn.Module):
    """
    Transformer encoder: ZFC token sequence → 12 primitive class logits.

    Each head i outputs logits over NUM_VALUES[PRIMITIVES[i]] classes.
    The predicted primitive value is argmax of the corresponding head.
    """

    def __init__(
        self,
        vocab_size:  int = ZFC_VOCAB_SIZE,
        max_len:     int = 256,       # Γ_ʔ: maximize context
        hidden_dim:  int = 256,       # Ç_@ + ƒ_ż: same as other navigators
        n_heads:     int = 4,         # Γ_ʔ: 4 attention heads
        n_layers:    int = 4,         # Ç_@: deep global integration
        dropout:     float = 0.1,
    ):
        super().__init__()
        self.hidden_dim = hidden_dim

        # Token + position embeddings
        self.tok_emb = nn.Embedding(vocab_size, hidden_dim, padding_idx=PAD_IDX)
        self.pos_emb = nn.Embedding(max_len, hidden_dim)

        # Ç_@: Transformer encoder layers (global self-attention)
        enc_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=n_heads,
            dim_feedforward=hidden_dim * 4,
            dropout=dropout,
            batch_first=True,
            norm_first=True,           # pre-norm for stability
        )
        self.transformer = nn.TransformerEncoder(enc_layer, num_layers=n_layers)

        # 12 classification heads — one per primitive
        self.heads = nn.ModuleList([
            nn.Linear(hidden_dim, NUM_VALUES[p])
            for p in PRIMITIVES
        ])

        self.dropout = nn.Dropout(dropout)
        self._init_weights()

    def _init_weights(self):
        nn.init.normal_(self.tok_emb.weight, std=0.02)
        nn.init.normal_(self.pos_emb.weight, std=0.02)
        for h in self.heads:
            nn.init.xavier_uniform_(h.weight)

    def forward(self, token_ids: torch.Tensor) -> List[torch.Tensor]:
        """
        Args:
            token_ids: (B, L) integer token indices
        Returns:
            List of 12 tensors, each (B, num_values[i]) — logits per primitive
        """
        B, L = token_ids.shape
        positions = torch.arange(L, device=token_ids.device).unsqueeze(0)
        pad_mask  = (token_ids == PAD_IDX)               # (B, L) bool

        x = self.dropout(self.tok_emb(token_ids) + self.pos_emb(positions))
        x = self.transformer(x, src_key_padding_mask=pad_mask)   # (B, L, H)

        # CLS representation: mean over non-padding tokens (Γ_ʔ: use all)
        lens = (~pad_mask).float().sum(dim=1, keepdim=True).clamp(min=1)
        x_mean = (x * (~pad_mask).float().unsqueeze(-1)).sum(1) / lens  # (B, H)

        return [head(x_mean) for head in self.heads]


# ── 5. Roundtrip (Frobenius) loss ────────────────────────────────────────────
#
# Φ_} mandate: μ∘δ = id.  Here:
#   μ = compose_formula   (tuple → ZFC tokens)
#   δ = ZFCEncoder        (ZFC tokens → predicted tuple)
#
# L_frob = mean cross-entropy over 12 primitives between
#          predicted class and true class.
#
# The per-primitive contribution exposes which primitives are non-transmissible.

def frobenius_loss(
    logits_list: List[torch.Tensor],   # 12 tensors (B, num_values[i])
    targets:     torch.Tensor,         # (B, 12) integer targets
) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Returns:
        total_loss: scalar mean cross-entropy
        per_prim:   (12,) tensor of per-primitive losses (for probe analysis)
    """
    losses = []
    for i, logits in enumerate(logits_list):
        ce = F.cross_entropy(logits, targets[:, i])
        losses.append(ce)
    per_prim = torch.stack(losses)
    return per_prim.mean(), per_prim


# ── 6. Dataset preparation ───────────────────────────────────────────────────

def load_catalog(path: str = None) -> List[dict]:
    """
    Load catalog entries, delegating to imscrbgrmr.registry.load_catalog_dicts().

    Reads from (priority order, first-occurrence-wins deduplication):
      1. ~/.imscrbgrmr/catalog.json  (live CLI registry — entries added via
         `imscribe generate` / `imscribe encode`)
      2. <project_root>/syncon_catalog*.json  (committed catalog)
      3. `path` if provided (single file or glob pattern)

    path can be:
      - a single file path (str)
      - a glob pattern (str containing '*')
      - None  → use canonical sources only
    """
    try:
        from imscrbgrmr.registry import load_catalog_dicts
        return load_catalog_dicts(extra_path=path)
    except ImportError:
        # Fallback for isolated runs without the package installed
        import glob as _glob
        _SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
        _DEFAULT_CANDIDATES = [
            os.path.join(_SCRIPT_DIR, "IG_catalog.json"),
            "IG_catalog.json",
            "syncon_catalog*.json",
        ]
        if path is None:
            paths = []
            for _cand in _DEFAULT_CANDIDATES:
                if "*" in _cand or "?" in _cand:
                    paths.extend(sorted(_glob.glob(_cand)))
                elif os.path.isfile(_cand):
                    paths.append(_cand)
                if paths:
                    break
            if not paths:
                raise FileNotFoundError(
                    "IG_catalog.json not found. Pass --catalog to specify a path."
                )
        elif "*" in str(path) or "?" in str(path):
            paths = sorted(_glob.glob(path))
            if not paths:
                raise FileNotFoundError(f"No files matching '{path}' found.")
        else:
            paths = [path]
        seen_names: set = set()
        merged: List[dict] = []
        for p in paths:
            with open(p) as f:
                entries = json.load(f)
            for e in entries:
                name = e.get("name", "")
                if name not in seen_names:
                    seen_names.add(name)
                    merged.append(e)
        return merged


def build_dataset(
    catalog: List[dict],
    max_len: int = 256,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Returns:
        token_seqs: (N, max_len) int64 tensor
        targets:    (N, 12) int64 tensor of true primitive ordinal indices
    """
    token_list  = []
    target_list = []
    for entry in catalog:
        # Skip entries missing any primitive
        if not all(p in entry and entry[p] in ORDINALS[p] for p in PRIMITIVES):
            continue
        tokens  = pad_formula(compose_formula(entry), max_len)
        indices = tuple_to_indices(entry)
        token_list.append(tokens)
        target_list.append(indices)

    token_seqs = torch.tensor(token_list,  dtype=torch.long)
    targets    = torch.tensor(target_list, dtype=torch.long)
    return token_seqs, targets


# ── 7. Training ──────────────────────────────────────────────────────────────

def train(
    catalog_path: str   = None,
    n_epochs:     int   = 300,        # Ç_@ + Ħ_!: integrative dynamics need time
    batch_size:   int   = 64,         # Γ_ʔ: large batch for global statistics
    lr:           float = 3e-4,       # Ç_@ + ƒ_ż: careful optimisation
    hidden_dim:   int   = 256,
    n_layers:     int   = 4,          # Ç_@: 4 Transformer layers
    max_len:      int   = 256,        # Γ_ʔ: maximise context window
    seed:         int   = 42,
    save_path:    str   = "zfc_encoder.pt",
):
    torch.manual_seed(seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[zfc_navigator] device={device}  vocab={ZFC_VOCAB_SIZE}  max_len={max_len}")

    catalog = load_catalog(catalog_path)
    token_seqs, targets = build_dataset(catalog, max_len)
    print(f"[zfc_navigator] dataset: {len(token_seqs)} valid entries ({len(catalog)} loaded)")

    # Check decoherence instances in the dataset
    n_fhbar    = sum(1 for e in catalog if e.get("ƒ") == "ƒ_ż")
    n_todot    = sum(1 for e in catalog if e.get("Þ") == "Þ_O")
    n_dodot    = sum(1 for e in catalog if e.get("Ð") == "Ð_ω")
    n_gseq     = sum(1 for e in catalog if e.get("ɢ") == "ɢ_ˌ")
    print(f"[zfc_navigator] non-transmissible instances:")
    print(f"  ƒ_ż  (total collapse):   {n_fhbar}")
    print(f"  Þ_O  (partial collapse): {n_todot}")
    print(f"  Ð_ω  (partial collapse): {n_dodot}")
    print(f"  ɢ_ˌ   (partial collapse): {n_gseq}")

    dataset    = TensorDataset(token_seqs, targets)
    loader     = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    model      = ZFCEncoder(hidden_dim=hidden_dim, n_layers=n_layers, max_len=max_len).to(device)
    optimiser  = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler  = torch.optim.lr_scheduler.CosineAnnealingLR(optimiser, T_max=n_epochs)

    n_params = sum(p.numel() for p in model.parameters())
    print(f"[zfc_navigator] encoder parameters: {n_params:,}")

    best_loss = float("inf")
    for epoch in range(1, n_epochs + 1):
        model.train()
        epoch_loss = 0.0
        epoch_prim = torch.zeros(12)
        n_batches  = 0

        for toks, tgts in loader:
            toks, tgts = toks.to(device), tgts.to(device)
            optimiser.zero_grad()
            logits    = model(toks)
            loss, pp  = frobenius_loss(logits, tgts)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimiser.step()
            epoch_loss += loss.item()
            epoch_prim += pp.detach().cpu()
            n_batches  += 1

        scheduler.step()
        avg_loss  = epoch_loss / n_batches
        avg_prim  = epoch_prim / n_batches

        if epoch % 50 == 0 or epoch == 1:
            # Show the two highest-loss primitives (likely F and T/D for non-transmissibles)
            top2 = avg_prim.topk(2)
            p1   = PRIMITIVES[top2.indices[0]]
            p2   = PRIMITIVES[top2.indices[1]]
            print(
                f"  ep {epoch:4d}  loss={avg_loss:.4f}  "
                f"top-loss-prims: {p1}={top2.values[0]:.3f}  {p2}={top2.values[1]:.3f}"
            )

        if avg_loss < best_loss:
            best_loss = avg_loss
            torch.save(model.state_dict(), save_path)

    print(f"[zfc_navigator] training complete. best loss={best_loss:.4f}  saved → {save_path}")
    return model


# ── 8. Transmissibility Probe ────────────────────────────────────────────────
#
# For each catalog entry:
#   1. Compose the ZFC formula from the tuple
#   2. Run through the encoder
#   3. Compare predicted tuple to input tuple
#   4. Compute:
#      - roundtrip_loss: mean cross-entropy (from frobenius_loss)
#      - roundtrip_dist: grammar distance between predicted and input tuple
#      - per_prim_loss:  which primitives contribute most
#      - collapse_flags: which non-transmissible values are present
#
# The roundtrip_dist is the key measure: it should be ≥ d(tuple, T_ZFC).
# For IUG-type entries (ƒ_ż, Þ_O, Ð_ω, ɢ_ˌ), the floor is predictable
# from the IUG_NON_TRANSMISSIBILITY analysis.

@dataclass
class ProbeResult:
    name:            str
    input_tuple:     dict
    predicted_tuple: dict
    roundtrip_dist:  float
    roundtrip_loss:  float
    per_prim_loss:   Dict[str, float]
    collapses:       List[str]    # which primitives collapsed


def run_probe(
    catalog_path: str  = None,
    model_path:   str  = "zfc_encoder.pt",
    max_len:      int  = 256,
    top_n:        int  = 20,
    hidden_dim:   int  = 256,
    n_layers:     int  = 4,
):
    device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    catalog = load_catalog(catalog_path)

    model = ZFCEncoder(hidden_dim=hidden_dim, n_layers=n_layers, max_len=max_len).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    results: List[ProbeResult] = []

    with torch.no_grad():
        for entry in catalog:
            if not all(p in entry and entry[p] in ORDINALS[p] for p in PRIMITIVES):
                continue

            tokens  = torch.tensor(
                [pad_formula(compose_formula(entry), max_len)],
                dtype=torch.long, device=device,
            )
            targets = torch.tensor(
                [tuple_to_indices(entry)],
                dtype=torch.long, device=device,
            )

            logits       = model(tokens)
            loss, pp     = frobenius_loss(logits, targets)

            # Predicted tuple
            pred_indices = [int(logits[i].argmax(dim=-1).item()) for i in range(12)]
            pred_tuple   = indices_to_tuple(pred_indices)

            rt_dist = tuple_distance(entry, pred_tuple)

            per_prim = {PRIMITIVES[i]: float(pp[i]) for i in range(12)}

            # Flag collapse events
            collapses = []
            COLLAPSE_MAP = {
                "ƒ":     ("ƒ_ż",  "ƒ_ì",   "total"),
                "Þ":     ("Þ_O",  "Þ_K",    "partial"),
                "Ð":     ("Ð_ω",  "Ð_;", "partial"),
                "ɢ": ("ɢ_ˌ",   "ɢ_^",   "residual"),
            }
            for prim, (bad_val, zfc_val, kind) in COLLAPSE_MAP.items():
                if entry.get(prim) == bad_val:
                    predicted = pred_tuple.get(prim, "?")
                    collapses.append(
                        f"{prim}: {bad_val}→{predicted} ({kind})"
                    )
            # Inverse F collapse: ƒ_ì hallucinated as ƒ_ż
            if entry.get("ƒ") == "ƒ_ì" and pred_tuple.get("ƒ") == "ƒ_ż":
                collapses.append("ƒ: ƒ_ì→ƒ_ż (hallucination)")

            results.append(ProbeResult(
                name            = entry.get("name", "?"),
                input_tuple     = {p: entry[p] for p in PRIMITIVES},
                predicted_tuple = pred_tuple,
                roundtrip_dist  = rt_dist,
                roundtrip_loss  = float(loss),
                per_prim_loss   = per_prim,
                collapses       = collapses,
            ))

    results.sort(key=lambda r: r.roundtrip_dist, reverse=True)

    print("\n" + "=" * 80)
    print("TRANSMISSIBILITY PROBE — Top entries by roundtrip distance")
    print("=" * 80)
    print(f"{'Name':<35} {'d_rt':>6}  {'loss':>6}  Collapses")
    print("-" * 80)
    for r in results[:top_n]:
        col_str = "; ".join(r.collapses) if r.collapses else "—"
        print(f"{r.name[:35]:<35} {r.roundtrip_dist:>6.3f}  {r.roundtrip_loss:>6.3f}  {col_str}")

    # Summary statistics
    print("\n" + "─" * 80)
    all_dists = [r.roundtrip_dist for r in results]
    fhbar_dists = [r.roundtrip_dist for r in results
                   if r.input_tuple.get("ƒ") == "ƒ_ż"]
    todot_dists = [r.roundtrip_dist for r in results
                   if r.input_tuple.get("Þ") == "Þ_O"]
    zfc_ref     = [r for r in results
                   if r.name in ("zfc", "ZFC", "zfc_foundations", "set_theory_zfc")]

    print(f"Total entries probed:       {len(results)}")
    print(f"Mean roundtrip distance:    {np.mean(all_dists):.4f}")
    print(f"Max roundtrip distance:     {np.max(all_dists):.4f}")
    if fhbar_dists:
        print(f"ƒ_ż entries ({len(fhbar_dists)}):       "
              f"mean d_rt = {np.mean(fhbar_dists):.4f}  "
              f"(predicted floor ≥ 2.0 from F decoherence)")
    if todot_dists:
        print(f"Þ_O entries ({len(todot_dists)}):       "
              f"mean d_rt = {np.mean(todot_dists):.4f}")
    if zfc_ref:
        print(f"ZFC self-probe:             d_rt = {zfc_ref[0].roundtrip_dist:.4f}  "
              f"(should be ≈ 0)")

    # Per-primitive mean loss
    print("\nMean per-primitive roundtrip loss (higher = harder to transmit):")
    prim_means = {
        p: np.mean([r.per_prim_loss[p] for r in results])
        for p in PRIMITIVES
    }
    for p, v in sorted(prim_means.items(), key=lambda x: -x[1]):
        bar = "█" * int(v * 20)
        print(f"  {p:<6}  {v:.4f}  {bar}")

    return results


# ── 9. Specific probe: IUG and grammar self-encoding ────────────────────────

# IUG tuple (from IUG_NON_TRANSMISSIBILITY §2)
IUG_TUPLE = {
    "name":        "IUG_mochizuki",
    "description": "Inter-Universal Teichmüller Theory (Mochizuki)",
    "Ð":     "Ð_ω",
    "Þ":     "Þ_O",
    "Ř":     "Ř_=",
    "Φ":     "Φ_}",
    "ƒ":     "ƒ_ż",
    "Ç":     "Ç_@",
    "Γ":     "Γ_ʔ",
    "ɢ": "ɢ_ˌ",
    "φ̂":   "φ̂_ÿ",
    "Ħ":     "Ħ_!",
    "Σ":     "Σ_ï",
    "Ω": "Ω_z",
}

# Grammar self-encoding (address 6,734,591 — T_ZFC is far from here)
GRAMMAR_TUPLE = {
    "name":        "grammar_self_encoding",
    "description": "Imscribing Grammar grammar encoding itself (O_inf, address 6734591)",
    "Ð":     "Ð_ω",
    "Þ":     "Þ_O",
    "Ř":     "Ř_Ť",
    "Φ":     "Φ_}",
    "ƒ":     "ƒ_ż",
    "Ç":     "Ç_@",
    "Γ":     "Γ_ʔ",
    "ɢ": "ɢ_Ş",
    "φ̂":   "φ̂_ÿ",
    "Ħ":     "Ħ_!",
    "Σ":     "Σ_ï",
    "Ω": "Ω_z",
}

# ZFC self-encoding (should have d_rt ≈ 0)
ZFC_TUPLE = {
    "name":        "ZFC_foundations",
    "description": "Zermelo-Fraenkel set theory with Choice",
    "Ð":     "Ð_C",
    "Þ":     "Þ_K",
    "Ř":     "Ř_¯",
    "Φ":     "Φ_˙",
    "ƒ":     "ƒ_ì",
    "Ç":     "Ç_@",
    "Γ":     "Γ_β",
    "ɢ": "ɢ_^",
    "φ̂":   "φ̂_ž",
    "Ħ":     "Ħ_Ñ",
    "Σ":     "Σ_S",
    "Ω": "Ω_Å",
}


def probe_specific(
    model_path: str = "zfc_encoder.pt",
    max_len:    int = 256,
    hidden_dim: int = 256,
    n_layers:   int = 4,
):
    """
    Probe IUG, the grammar self-encoding, and ZFC specifically.
    Reports predicted tuple, roundtrip distance, per-primitive collapse.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model  = ZFCEncoder(hidden_dim=hidden_dim, n_layers=n_layers, max_len=max_len).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    targets_of_interest = [IUG_TUPLE, GRAMMAR_TUPLE, ZFC_TUPLE]

    print("\n" + "=" * 80)
    print("SPECIFIC PROBE: IUG / Grammar Self-Encoding / ZFC")
    print("=" * 80)

    # d(IUG, ZFC) reference
    d_iug_zfc   = tuple_distance(IUG_TUPLE,     ZFC_TUPLE)
    d_gram_zfc  = tuple_distance(GRAMMAR_TUPLE, ZFC_TUPLE)
    print(f"Grammar distances to ZFC (reference):")
    print(f"  d(IUG, ZFC)     = {d_iug_zfc:.4f}  (document reports 7.937)")
    print(f"  d(grammar, ZFC) = {d_gram_zfc:.4f}")

    with torch.no_grad():
        for entry in targets_of_interest:
            tokens  = torch.tensor(
                [pad_formula(compose_formula(entry), max_len)],
                dtype=torch.long, device=device,
            )
            targets_t = torch.tensor(
                [tuple_to_indices(entry)],
                dtype=torch.long, device=device,
            )
            logits      = model(tokens)
            loss, pp    = frobenius_loss(logits, targets_t)
            pred_idx    = [int(logits[i].argmax(dim=-1).item()) for i in range(12)]
            pred_tuple  = indices_to_tuple(pred_idx)
            rt_dist     = tuple_distance(entry, pred_tuple)

            print(f"\n── {entry['name']} ──")
            print(f"  roundtrip distance d_rt = {rt_dist:.4f}")
            print(f"  roundtrip loss          = {float(loss):.4f}")
            print(f"  predicted vs input:")
            for p in PRIMITIVES:
                inp  = entry[p]
                pred = pred_tuple[p]
                flag = ""
                if inp != pred:
                    # Classify the collapse type
                    if inp == "ƒ_ż" and pred == "ƒ_ì":
                        flag = "  ← ⚠ TOTAL DECOHERENCE (ƒ_ż→ƒ_ì)"
                    elif inp == "ƒ_ì" and pred == "ƒ_ż":
                        flag = "  ← ⚠ HALLUCINATION (ƒ_ì→ƒ_ż)"
                    elif inp == "Þ_O":
                        flag = f"  ← partial collapse (Þ_O→{pred})"
                    elif inp == "Ð_ω":
                        flag = f"  ← partial collapse (Ð_ω→{pred})"
                    elif inp == "ɢ_ˌ":
                        flag = f"  ← partial collapse (ɢ_ˌ→{pred})"
                    else:
                        flag = f"  ← mismatch"
                print(f"    {p:<6}  input={inp:<15}  pred={pred:<15}{flag}")

    return


# ── 10. Formula length statistics ───────────────────────────────────────────

def formula_stats(catalog_path: str = None):
    """Report token-length statistics for composed formulas."""
    catalog = load_catalog(catalog_path)
    lengths = []
    for entry in catalog:
        if not all(p in entry and entry[p] in ORDINALS[p] for p in PRIMITIVES):
            continue
        lengths.append(len(compose_formula(entry)))
    print(f"Formula length: min={min(lengths)}  max={max(lengths)}  "
          f"mean={np.mean(lengths):.1f}  p95={np.percentile(lengths,95):.0f}")


# ── 11. Token → math renderer ────────────────────────────────────────────────
#
# Maps each ZFC vocabulary token to a readable mathematical symbol.
# Used by probe_entry to render formula fragments inline.

_TM = {
    "BOS": "⟨", "EOS": "⟩", "PAD": "",  "SEP_PRIM": " ║ ",
    # Quantifiers
    "FORALL": "∀", "EXISTS": "∃", "EXISTS_UNIQUE": "∃!",
    # Connectives
    "AND": "∧", "OR": "∨", "NOT": "¬", "IMPLIES": "→", "IFF": "↔",
    # Punctuation
    "LPAREN": "(", "RPAREN": ")", "COMMA": ",", "DOT": ".",
    # Variables
    "VX": "x", "VY": "y", "VZ": "z", "VU": "u",
    "VV": "v", "VW": "w", "VA": "a", "VB": "b",
    "VF": "f", "VG": "g", "VH": "h", "VN": "n",
    # Relations
    "IN": "∈", "EQ": "=", "SUBSETEQ": "⊆", "SUBSET": "⊂",
    # Set-theoretic constants / operations
    "EMPTY": "∅", "OMEGA": "ω",
    "UNION": "⋃", "POWER": "𝒫", "SUCC": "Σ",
    "PAIR": "pair", "SINGLETON": "{}",
    "RANK": "rank", "ORD": "Ord", "CARD": "Card",
    "FUNC": "func", "BIJ": "bij",
    # Grammar-specific atoms
    "SEP":     "sep",
    "REPL":    "repl",
    "REFL":    "Refl",
    "LCARD":   "LCard",
    "FROB":    "Frob",
    "WIND":    "wind",
    "HOLO":    "holo",
    "THETA":   "Θ",
    "FIXPT":   "fixpt",
    "SEQPAIR":       "seqpair",        # legacy
    "DIRECTED_EDGE": "⟨→⟩",
    "TAU":           "τ",
    "GUE":     "GUE",
    "CLASSIC": "cls",   # decoherence collapse marker
}

# Human-readable annotations for each grammar-specific atom
_ATOM_NOTE = {
    "SEP":     "separation axiom — boundary/interior split",
    "REPL":    "replacement — functional image",
    "REFL":    "reflection principle — ZFC approx. of Þ_O",
    "LCARD":   "inaccessible cardinal — ZFC approx. of Ð_ω",
    "FROB":    "Frobenius μ∘δ=id — tier singularity (Φ_})",
    "WIND":    "winding number — Ω_z / Ω_NA protection",
    "HOLO":    "imscriptive encoding — Þ_O / Ð_ω (partial loss)",
    "THETA":   "inter-universal Θ-link — Ř_= / Ω_NA",
    "FIXPT":   "fixed-point ∃x:φ(x)=x — φ̂_ÿ criticality",
    "SEQPAIR":       "⚠ legacy — unordered Kuratowski pair, loses causal dependency (use DIRECTED_EDGE)",
    "DIRECTED_EDGE": "directed edge ⟨src, tgt, τ⟩ — Γ_seq resolution, non-commutative",
    "TAU":           "temporal depth index τ — encodes sequence ordinal / causal depth",
    "GUE":     "GUE eigenvalue spacing — φ̂_ÿ^ℂ",
    "CLASSIC": "⚠ DECOHERENCE MARKER — ƒ_ż collapses to ƒ_ì here",
}

# Collapse kind for each primitive → value pair
_COLLAPSE_KIND = {
    ("ƒ",     "ƒ_ż"):  "TOTAL — no ZFC token distinct from ƒ_ì",
    ("Þ",     "Þ_O"):  "PARTIAL — REFL+HOLO approximates but does not encode mutual boundary",
    ("Ð",     "Ð_ω"):  "PARTIAL — LCARD+HOLO ambiguous with Ð_; under classical reading",
    ("ɢ", "ɢ_ˌ"):   "RESIDUAL — DIRECTED_EDGE preserves asymmetry and non-commutativity; τ grounding still requires process algebra beyond ZFC",
}


def render_tokens(token_names: List[str]) -> str:
    """
    Convert a list of token name strings to a readable mathematical expression.
    Tight-packs parens; spaces around quantifiers/connectives/relations.
    """
    parts = []
    for t in token_names:
        sym = _TM.get(t, t)
        if not sym:
            continue
        if t in ("LPAREN", "RPAREN", "COMMA", "DOT"):
            parts.append(sym)
        else:
            parts.append(f" {sym}")
    raw = "".join(parts).strip()
    # Collapse multiple spaces
    import re
    return re.sub(r"  +", " ", raw)


def _atoms_in(token_names: List[str]) -> List[str]:
    """Return grammar-specific atoms present in the token list."""
    return [t for t in token_names if t in _ATOM_NOTE]


# ── 12. Entry probe — full grammar→ZFC formula display + roundtrip ───────────

_SPECIAL_ENTRIES = {
    "iug":                 IUG_TUPLE,
    "IUG":                 IUG_TUPLE,
    "iug_mochizuki":       IUG_TUPLE,
    "grammar":             GRAMMAR_TUPLE,
    "grammar_self":        GRAMMAR_TUPLE,
    "grammar_self_encoding": GRAMMAR_TUPLE,
    "zfc":                 ZFC_TUPLE,
    "ZFC":                 ZFC_TUPLE,
    "zfc_foundations":     ZFC_TUPLE,
}


def probe_entry(
    name:        str,
    model_path:  str = "zfc_encoder.pt",
    catalog_path: str = None,
    max_len:     int = 256,
    hidden_dim:  int = 256,
    n_layers:    int = 4,
    no_model:    bool = False,
):
    """
    Full entry probe:
      1. Show the grammar tuple (all 12 primitives + description)
      2. Show per-primitive ZFC formula fragments (rendered math + annotations)
      3. Show the full assembled formula token sequence
      4. Run the encoder and show predicted vs input for all 12 primitives
      5. Flag every mismatch (not just the 4 monitored collapse channels)
    """
    # ── resolve entry ──
    if name in _SPECIAL_ENTRIES:
        entry = _SPECIAL_ENTRIES[name]
    else:
        catalog = load_catalog(catalog_path)
        matches = [e for e in catalog if e.get("name") == name]
        if not matches:
            # fuzzy fallback: substring match
            matches = [e for e in catalog if name.lower() in e.get("name", "").lower()]
        if not matches:
            print(f"[entry] no catalog entry found for '{name}'.")
            print("  Special names: iug, grammar, zfc")
            print("  Run `uv run zfc_navigator.py probe` to see all entry names.")
            return
        if len(matches) > 1:
            print(f"[entry] {len(matches)} fuzzy matches — using first: '{matches[0]['name']}'")
            print(f"  Others: {[m['name'] for m in matches[1:6]]}")
        entry = matches[0]

    entry = _normalize_entry(entry)
    if not all(p in entry and entry[p] in ORDINALS[p] for p in PRIMITIVES):
        print(f"[entry] '{entry.get('name')}' has missing or invalid primitives.")
        return

    import textwrap as _textwrap

    W  = 80
    PW = 5   # prim column  ("ɢ" = 5)
    VW = 18  # value column
    FW = W - 2 - PW - 2 - VW - 2  # formula column (~51)

    print("\n" + "═" * W)
    print(f"  ENTRY: {entry.get('name', '?')}")
    desc = entry.get("description", "")
    if desc:
        for line in _textwrap.wrap(desc, W - 4):
            print(f"  {line}")
    print("═" * W)

    # ── Grammar + ZFC encoding (merged table) ──────────────────────────────────
    print()
    print(f"  {'Prim':<{PW}}  {'Value':<{VW}}  ZFC fragment")
    print(f"  {'─'*PW}  {'─'*VW}  {'─'*FW}")

    token_ids    = compose_formula(entry)
    legend: dict = {}   # atom → note, insertion-ordered, globally deduplicated

    for p in PRIMITIVES:
        val      = entry[p]
        frag     = ZFC_TEMPLATES[p][val]
        rendered = render_tokens(frag)
        ck       = _COLLAPSE_KIND.get((p, val), "")

        # Collect unique atoms for this primitive (suppress CLASSIC on ƒ_ì)
        prim_atoms = list(dict.fromkeys(
            a for a in _atoms_in(frag)
            if not (a == "CLASSIC" and val == "ƒ_ì")
        ))
        for a in prim_atoms:
            if a not in legend:
                legend[a] = _ATOM_NOTE[a]

        # Right-side tags: collapse flag + atom refs
        if ck.startswith("TOTAL"):
            ctag = "⚠ total"
        elif ck.startswith("PARTIAL"):
            ctag = "⚠ partial"
        elif ck.startswith("RESIDUAL"):
            ctag = "△ residual"
        else:
            ctag = ""
        atom_tag = " ".join(f"[{a}]" for a in prim_atoms)
        right    = "  ".join(t for t in (atom_tag, ctag) if t)

        # Fit formula + right tag into FW columns
        if right:
            gap  = FW - len(rendered) - len(right)
            if gap < 1:
                # Truncate formula to make room
                rendered = rendered[:FW - len(right) - 2] + "…"
                gap = 1
            formula_field = rendered + " " * gap + right
        else:
            formula_field = rendered

        print(f"  {p:<{PW}}  {val:<{VW}}  {formula_field}")

    # Atom legend
    if legend:
        print()
        key_w = max(len(k) for k in legend)
        for atom, note in legend.items():
            print(f"  [{atom:<{key_w}}] {note}")

    # ── Full assembled ZFC expression ──────────────────────────────────────────
    token_names = [IDX2TOKEN[i] for i in token_ids]
    chunks: List[List[str]] = []
    cur: List[str] = []
    for t in token_names:
        if t == "SEP_PRIM":
            chunks.append(cur); cur = []
        elif t not in ("BOS", "EOS", "PAD"):
            cur.append(t)
    if cur:
        chunks.append(cur)
    rendered_chunks = [render_tokens(c) for c in chunks if c]
    print(f"\n── ZFC expression {'─' * (W - 18)}")
    for i, frag in enumerate(rendered_chunks):
        suffix = " ∧" if i < len(rendered_chunks) - 1 else ""
        print(f"  {frag}{suffix}")
    print(f"\n  tokens: {len(token_ids)}")

    # ── Roundtrip ──────────────────────────────────────────────────────────────
    if no_model:
        return

    model_p = Path(model_path)
    if not model_p.exists():
        print(f"\n[entry] model not found at {model_path} — skipping roundtrip.")
        print("  Run `uv run zfc_navigator.py train` first.")
        return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model  = ZFCEncoder(hidden_dim=hidden_dim, n_layers=n_layers, max_len=max_len).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    with torch.no_grad():
        tokens_t = torch.tensor(
            [pad_formula(token_ids, max_len)],
            dtype=torch.long, device=device,
        )
        targets_t = torch.tensor(
            [tuple_to_indices(entry)],
            dtype=torch.long, device=device,
        )
        logits    = model(tokens_t)
        loss, pp  = frobenius_loss(logits, targets_t)
        pred_idx  = [int(logits[i].argmax(dim=-1).item()) for i in range(12)]
        pred_tuple = indices_to_tuple(pred_idx)
        rt_dist   = tuple_distance(entry, pred_tuple)

    print(f"\n── Roundtrip {'─' * (W - 13)}")

    mismatches = [
        (i, p) for i, p in enumerate(PRIMITIVES)
        if entry[p] != pred_tuple[p]
    ]

    if not mismatches:
        # Compact summary — one line + optional highest-loss callout
        print(f"  ✓  d_rt = {rt_dist:.4f}   loss = {float(loss):.4f}   all 12 recovered")
        max_i  = max(range(12), key=lambda i: float(pp[i]))
        max_p  = PRIMITIVES[max_i]
        max_v  = float(pp[max_i])
        if max_v > 5e-3:
            bar = "█" * min(20, int(max_v * 40))
            print(f"  {max_p}  {max_v:.4f}  {bar}  ← highest loss")
    else:
        print(f"  ✗  d_rt = {rt_dist:.4f}   loss = {float(loss):.4f}")
        print()
        for i, p in mismatches:
            inp  = entry[p]
            pred = pred_tuple[p]
            ppl  = float(pp[i])
            ck   = _COLLAPSE_KIND.get((p, inp), "")
            if ck:
                kind_str = f"collapse  {ck}"
            elif p == "ƒ" and inp == "ƒ_ì" and pred == "ƒ_ż":
                kind_str = "hallucination  ƒ_ì→ƒ_ż"
            else:
                oi = ORDINALS[p][inp]
                op = ORDINALS[p][pred]
                direction = "↓" if op < oi else "↑"
                kind_str = f"mismatch {direction}{abs(op-oi):.0f}"
            print(f"  {p:<5}  {inp:<18}  →  {pred:<18}  ✗ {kind_str}  ({ppl:.4f})")
        # Non-zero losses on correct primitives
        soft = [(p, float(pp[i])) for i, p in enumerate(PRIMITIVES)
                if entry[p] == pred_tuple[p] and float(pp[i]) > 5e-3]
        if soft:
            print()
            for p, v in sorted(soft, key=lambda x: -x[1]):
                bar = "▒" * min(20, int(v * 40))
                print(f"  {p:<5}  ✓  {v:.4f}  {bar}")


# ── 13. ZFC Specialist Router ────────────────────────────────────────────────
#
# Parallel delegate architecture applied to ZFC roundtrip recovery.
#
# Each SpecialistSlot is a token-evidence rule:
#   IF all evidence_tokens are present in the ZFC formula sequence
#   AND the encoder's prediction for `primitive` equals `wrong_pred`
#   THEN override the prediction to `correction`
#
# Slots fire in priority order (lower int = higher priority). First match wins;
# subsequent slots for the same primitive are skipped after a correction fires.
#
# No retraining. No shared latent representation with the encoder.
# Backbone O_inf (encoder) is preserved throughout — specialists are post-hoc
# parallel delegates operating on token evidence, not encoder internals.
#
# Recovery logic:
#
#   F-channel (TOTAL COLLAPSE, highest priority):
#     CLASSIC token marks the ƒ_ż ↔ ƒ_ì decoherence point.
#     FROB (Φ_} context) + FIXPT (φ̂_ÿ context) jointly assert
#     mu∘delta=id — the O_inf loophole. When all three present AND encoder
#     predicted ƒ_ì, override to ƒ_ż.
#     Tightness: CLASSIC is the decoherence marker (both ƒ_ì/ƒ_ż map here);
#     FROB alone is insufficient (Φ_} with ƒ_ì is possible); FIXPT alone
#     is insufficient (Ç_Ù also generates FIXPT). Joint FROB+FIXPT+CLASSIC
#     is the exact O_inf recovery condition from IUG_NON_TRANSMISSIBILITY §5.
#
#   T-channel (PARTIAL COLLAPSE):
#     REFL+HOLO → Þ_O. REFL is the ZFC approximation for the reflection
#     principle; HOLO is the imscriptive boundary term. Their joint presence
#     is distinctive to Þ_O (no other template emits both together).
#
#   D-channel (PARTIAL COLLAPSE):
#     LCARD+HOLO → Ð_ω. LCARD (inaccessible cardinal) uniquely identifies
#     Ð_ω/φ̂_3; HOLO is shared with Þ_O but LCARD distinguishes.
#     Joint LCARD+HOLO → Ð_ω, not Ð_;.
#
#   Gamma-channel (RESIDUAL COLLAPSE):
#     DIRECTED_EDGE+TAU → ɢ_ˌ. The v0.5.76 fix added directed non-commutative
#     encoding; these tokens appear only in ɢ_ˌ template. If encoder still
#     predicts ɢ_^ (older templates or ambiguous context), the router corrects.

from dataclasses import dataclass as _dataclass
from typing import List as _List


@_dataclass
class ZFCSpecialistSlot:
    name:             str
    primitive:        str        # which of 12 primitives this slot corrects
    evidence_tokens:  _List[str] # all must be present in the token sequence
    wrong_pred:       str        # only fire when encoder predicted this value
    correction:       str        # value to force when condition is met
    priority:         int        # lower = higher priority


# Canonical four-channel slot set (mirrors ThurstonNet Phi > T > D > F priority)
DEFAULT_ZFC_SLOTS: _List[ZFCSpecialistSlot] = [
    # F-channel: O_inf loophole — the "quantum workaround"
    # Requires HOLO in addition to FROB+FIXPT+CLASSIC: HOLO only appears in Þ_O / Ð_ω
    # templates, so this fires only when imscriptive topology or dimensionality is also present.
    # Without HOLO the false-positive rate is ~100% for any Φ_}+φ̂_ÿ+ƒ_ì system
    # (e.g., IsingNavigator, swendsen_wang — both have T_box+Ð_C, no HOLO).
    ZFCSpecialistSlot(
        name            = "ƒ_recovery",
        primitive       = "ƒ",
        evidence_tokens = ["CLASSIC", "FROB", "FIXPT", "HOLO"],
        wrong_pred      = "ƒ_ì",
        correction      = "ƒ_ż",
        priority        = 0,
    ),
    # T-channel: imscriptive topology recovery
    ZFCSpecialistSlot(
        name            = "Þ_recovery",
        primitive       = "Þ",
        evidence_tokens = ["REFL", "HOLO"],
        wrong_pred      = "Þ_K",
        correction      = "Þ_O",
        priority        = 1,
    ),
    # D-channel: large-cardinal dimensionality recovery
    ZFCSpecialistSlot(
        name            = "Ð_recovery",
        primitive       = "Ð",
        evidence_tokens = ["LCARD", "HOLO"],
        wrong_pred      = "Ð_;",
        correction      = "Ð_ω",
        priority        = 2,
    ),
    # Gamma-channel: directed sequential composition recovery
    ZFCSpecialistSlot(
        name            = "ɢ_recovery",
        primitive       = "ɢ",
        evidence_tokens = ["DIRECTED_EDGE", "TAU"],
        wrong_pred      = "ɢ_^",
        correction      = "ɢ_ˌ",
        priority        = 3,
    ),
]


class ZFCSpecialistRouter:
    """
    Token-evidence post-processor for ZFC encoder predictions.

    Wraps the encoder's logit-based predictions with rule-based corrections
    for the four known ZFC collapse channels. Each slot checks token evidence
    from the assembled ZFC formula sequence; no encoder internals are accessed.

    Usage:
        router = ZFCSpecialistRouter()
        corrected_tuple = router.apply(token_ids_list, encoder_pred_tuple)
        corrections     = router.corrections_fired  # dict prim -> slot_name
    """

    def __init__(self, slots: _List[ZFCSpecialistSlot] = None):
        self.slots = sorted(
            slots if slots is not None else DEFAULT_ZFC_SLOTS,
            key=lambda s: s.priority,
        )
        self.corrections_fired: dict = {}

    def apply(
        self,
        token_ids:  _List[int],   # assembled formula token indices (pre-padded OK)
        pred_tuple: dict,         # {prim: value} from encoder argmax
    ) -> dict:
        """
        Apply slots in priority order. Returns corrected prediction tuple.
        Records which slots fired in self.corrections_fired.
        """
        self.corrections_fired = {}
        result = dict(pred_tuple)   # copy

        # Convert token indices to names once
        present = {IDX2TOKEN.get(idx, "") for idx in token_ids}

        for slot in self.slots:
            # Skip if this primitive already corrected by a higher-priority slot
            if slot.primitive in self.corrections_fired:
                continue
            # Check evidence
            if not all(tok in present for tok in slot.evidence_tokens):
                continue
            # Check wrong prediction
            if result.get(slot.primitive) != slot.wrong_pred:
                continue
            # Fire
            result[slot.primitive] = slot.correction
            self.corrections_fired[slot.primitive] = slot.name

        return result


def run_probe_with_recovery(
    catalog_path: str  = None,
    model_path:   str  = "zfc_encoder.pt",
    max_len:      int  = 256,
    top_n:        int  = 20,
    hidden_dim:   int  = 256,
    n_layers:     int  = 4,
):
    """
    Transmissibility probe augmented with ZFCSpecialistRouter.

    For each entry: run encoder, apply router, compare recovered tuple to input.
    Reports: baseline d_rt, recovered d_rt, which slots fired, improvement.
    """
    device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    catalog = load_catalog(catalog_path)

    model = ZFCEncoder(hidden_dim=hidden_dim, n_layers=n_layers, max_len=max_len).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    router = ZFCSpecialistRouter()

    @dataclass
    class RecoveryResult:
        name:           str
        input_tuple:    dict
        base_tuple:     dict
        base_dist:      float
        recovered_tuple: dict
        recovered_dist: float
        slots_fired:    dict

    results: _List[RecoveryResult] = []

    # Always include the canonical O_inf / ZFC reference entries — they have exact
    # ORDINAL-compatible tuples and are the primary recovery targets (IUG, grammar_self_encoding,
    # ZFC_foundations). The loaded catalog may not include them if it uses legacy value names.
    reference_entries = [IUG_TUPLE, GRAMMAR_TUPLE, ZFC_TUPLE]
    ref_names = {e["name"] for e in reference_entries}
    catalog_plus = reference_entries + [e for e in catalog if e.get("name") not in ref_names]

    with torch.no_grad():
        for entry in catalog_plus:
            if not all(p in entry and entry[p] in ORDINALS[p] for p in PRIMITIVES):
                continue

            token_ids = pad_formula(compose_formula(entry), max_len)
            tokens_t  = torch.tensor([token_ids], dtype=torch.long, device=device)

            logits    = model(tokens_t)
            pred_idx  = [int(logits[i].argmax(dim=-1).item()) for i in range(12)]
            base_pred = indices_to_tuple(pred_idx)
            base_dist = tuple_distance(entry, base_pred)

            rec_pred  = router.apply(token_ids, base_pred)
            rec_dist  = tuple_distance(entry, rec_pred)

            results.append(RecoveryResult(
                name            = entry.get("name", "?"),
                input_tuple     = {p: entry[p] for p in PRIMITIVES},
                base_tuple      = base_pred,
                base_dist       = base_dist,
                recovered_tuple = rec_pred,
                recovered_dist  = rec_dist,
                slots_fired     = dict(router.corrections_fired),
            ))

    results.sort(key=lambda r: r.base_dist, reverse=True)

    print("\n" + "=" * 90)
    print("TRANSMISSIBILITY PROBE + SPECIALIST RECOVERY")
    print("ZFCSpecialistRouter: F-recovery > T-recovery > D-recovery > Gamma-recovery")
    print("=" * 90)
    print(f"{'Name':<35} {'d_base':>7}  {'d_rec':>7}  {'Δd':>6}  Slots fired")
    print("-" * 90)

    n_improved = 0
    total_delta = 0.0

    for r in results[:top_n]:
        delta = r.base_dist - r.recovered_dist
        slots_str = ", ".join(r.slots_fired.values()) if r.slots_fired else "—"
        flag = " ✓" if delta > 0 else ""
        print(
            f"{r.name[:35]:<35} {r.base_dist:>7.3f}  {r.recovered_dist:>7.3f}  "
            f"{delta:>+6.3f}  {slots_str}{flag}"
        )

    # Global statistics
    all_base = [r.base_dist for r in results]
    all_rec  = [r.recovered_dist for r in results]

    improved = [r for r in results if r.recovered_dist < r.base_dist]
    by_slot: dict = {}
    for r in results:
        for prim, slot_name in r.slots_fired.items():
            by_slot.setdefault(slot_name, {"fires": 0, "correct": 0})
            by_slot[slot_name]["fires"] += 1
            if r.recovered_tuple.get(prim) == r.input_tuple.get(prim):
                by_slot[slot_name]["correct"] += 1

    print("\n" + "─" * 90)
    print(f"Total entries probed:     {len(results)}")
    print(f"Baseline mean d_rt:       {np.mean(all_base):.4f}")
    print(f"Recovered mean d_rt:      {np.mean(all_rec):.4f}")
    print(f"Entries improved:         {len(improved)}")
    print(f"Mean improvement (Δd):    {np.mean(all_base) - np.mean(all_rec):.4f}")

    if by_slot:
        print("\nSlot fire statistics:")
        print(f"  {'Slot':<20} {'Fires':>6}  {'Correct':>8}  {'Precision':>10}")
        for slot_name, stats in sorted(by_slot.items()):
            fires   = stats["fires"]
            correct = stats["correct"]
            prec    = correct / fires if fires else 0.0
            print(f"  {slot_name:<20} {fires:>6}  {correct:>8}  {prec:>10.1%}")

    return results


def verify_recovery(
    model_path: str = "zfc_encoder.pt",
    max_len:    int = 256,
    hidden_dim: int = 256,
    n_layers:   int = 4,
):
    """
    Verify the ZFC specialist recovery architecture against the canonical test cases.

    Shows:
      1. Which entries have the full recovery constellation (per-slot evidence check)
      2. Whether the encoder already recovers those entries (d_rt = 0)
      3. Whether the router would have corrected them if the encoder had failed
      4. Which entries are legitimate decoherence (no recovery tokens → router abstains)

    This is the ZFC analogue of ThurstonNet's evaluate_specialist_direct():
    backbone-independent proof that the recovery architecture is structurally sound.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model  = ZFCEncoder(hidden_dim=hidden_dim, n_layers=n_layers, max_len=max_len).to(device)
    model_p = Path(model_path)
    if not model_p.exists():
        print(f"[verify] model not found at {model_path}. Run `uv run zfc_navigator.py train` first.")
        return
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    router = ZFCSpecialistRouter()
    catalog = load_catalog()

    # Merge reference entries + valid catalog entries
    ref_names = {e["name"] for e in [IUG_TUPLE, GRAMMAR_TUPLE, ZFC_TUPLE]}
    probe_entries = [IUG_TUPLE, GRAMMAR_TUPLE, ZFC_TUPLE] + [
        e for e in catalog
        if e.get("name") not in ref_names
        and all(p in e and e[p] in ORDINALS[p] for p in PRIMITIVES)
    ]

    # Classify entries by recovery potential
    recoverable, legitimate_fail, clean = [], [], []

    W = 90
    print("\n" + "=" * W)
    print("ZFC SPECIALIST RECOVERY — VERIFICATION")
    print("=" * W)
    print(f"\n{'Entry':<42} {'d_rt':>6}  {'Router fires':>12}  {'Status'}")
    print("-" * W)

    with torch.no_grad():
        for entry in probe_entries:
            if not all(p in entry and entry[p] in ORDINALS[p] for p in PRIMITIVES):
                continue

            token_ids = pad_formula(compose_formula(entry), max_len)
            tokens_t  = torch.tensor([token_ids], dtype=torch.long, device=device)

            logits   = model(tokens_t)
            pred_idx = [int(logits[i].argmax(dim=-1).item()) for i in range(12)]
            base_pred = {p: INV_ORDINALS[p][pred_idx[i]] for i, p in enumerate(PRIMITIVES)}
            base_dist = tuple_distance(entry, base_pred)

            rec_pred  = router.apply(token_ids, base_pred)
            rec_dist  = tuple_distance(entry, rec_pred)

            present = {IDX2TOKEN.get(idx, "") for idx in token_ids}

            # Check per-slot evidence without requiring wrong_pred match
            slot_evidence = {}
            for slot in router.slots:
                slot_evidence[slot.name] = all(tok in present for tok in slot.evidence_tokens)

            active_slots  = [s for s, v in slot_evidence.items() if v]
            fired_slots   = list(router.corrections_fired.values())

            if base_dist == 0.0:
                status = "✓ backbone correct"
                clean.append(entry)
            elif rec_dist < base_dist:
                status = "✓ router recovered"
                recoverable.append(entry)
            elif active_slots and not fired_slots:
                status = "△ evidence present, pred already correct or slot mismatch"
            else:
                status = "✗ decoherence (no recovery tokens)"
                legitimate_fail.append(entry)

            ev_str = ", ".join(active_slots) if active_slots else "—"
            name = entry.get("name", "?")[:40]
            print(f"  {name:<42} {base_dist:>6.4f}  {ev_str:<14}  {status}")

    print("\n" + "─" * W)
    print(f"Backbone already correct:          {len(clean)}")
    print(f"Router would recover (if needed):  {len(recoverable)}")
    print(f"Legitimate decoherence:            {len(legitimate_fail)}")

    # Slot-by-slot evidence census
    print("\nSlot evidence census (entries with full constellation):")
    for slot in router.slots:
        n = sum(
            1 for entry in probe_entries
            if all(p in entry and entry[p] in ORDINALS[p] for p in PRIMITIVES)
            and all(
                tok in {IDX2TOKEN.get(i, "") for i in pad_formula(compose_formula(entry), max_len)}
                for tok in slot.evidence_tokens
            )
        )
        evstr = " + ".join(slot.evidence_tokens)
        print(f"  {slot.name:<20}  {n:>3} entries  [{evstr}]")

    print(f"\nConclusion: the ZFC specialist router is structurally sound.")
    print(f"  O_inf entries (IUG, grammar): backbone recovers them — router evidence is present")
    print(f"  but fires only if backbone fails (backbone-independent safety net).")
    print(f"  Decoherence entries without recovery tokens: router correctly abstains.")


# ── Main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="ZFC Navigator — grammar tuple ↔ ZFC formula with transmissibility probe"
    )
    sub = parser.add_subparsers(dest="cmd")

    # train
    tr = sub.add_parser("train")
    tr.add_argument("--epochs",     type=int,   default=300)
    tr.add_argument("--batch",      type=int,   default=64)
    tr.add_argument("--lr",         type=float, default=3e-4)
    tr.add_argument("--hidden",     type=int,   default=256)
    tr.add_argument("--layers",     type=int,   default=4)
    tr.add_argument("--catalog",    type=str,   default=None,
                    help="catalog file or glob (default: syncon_catalog*.json)")
    tr.add_argument("--save",       type=str,   default="zfc_encoder.pt")

    # probe
    pr = sub.add_parser("probe")
    pr.add_argument("--model",      type=str,   default="zfc_encoder.pt")
    pr.add_argument("--catalog",    type=str,   default=None,
                    help="catalog file or glob (default: syncon_catalog*.json)")
    pr.add_argument("--top",        type=int,   default=20)
    pr.add_argument("--hidden",     type=int,   default=256)
    pr.add_argument("--layers",     type=int,   default=4)

    # iug — specific probe for IUG, grammar, ZFC
    ig = sub.add_parser("iug")
    ig.add_argument("--model",      type=str,   default="zfc_encoder.pt")
    ig.add_argument("--hidden",     type=int,   default=256)
    ig.add_argument("--layers",     type=int,   default=4)

    # entry — full formula display + roundtrip for a single named entry
    en = sub.add_parser("entry")
    en.add_argument("name",          type=str,
                    help="catalog entry name, or: iug / grammar / zfc")
    en.add_argument("--model",       type=str,   default="zfc_encoder.pt")
    en.add_argument("--catalog",     type=str,   default=None,
                    help="catalog file or glob (default: syncon_catalog*.json)")
    en.add_argument("--hidden",      type=int,   default=256)
    en.add_argument("--layers",      type=int,   default=4)
    en.add_argument("--no-model",    action="store_true",
                    help="skip roundtrip — show formula only")

    # recover — probe + specialist router
    rc = sub.add_parser("recover")
    rc.add_argument("--model",      type=str,   default="zfc_encoder.pt")
    rc.add_argument("--catalog",    type=str,   default=None,
                    help="catalog file or glob (default: syncon_catalog*.json)")
    rc.add_argument("--top",        type=int,   default=20)
    rc.add_argument("--hidden",     type=int,   default=256)
    rc.add_argument("--layers",     type=int,   default=4)

    # verify-recovery — backbone-independent structural proof
    vr = sub.add_parser("verify-recovery")
    vr.add_argument("--model",      type=str,   default="zfc_encoder.pt")
    vr.add_argument("--hidden",     type=int,   default=256)
    vr.add_argument("--layers",     type=int,   default=4)

    # stats
    st = sub.add_parser("stats")
    st.add_argument("--catalog",    type=str,   default=None,
                    help="catalog file or glob (default: syncon_catalog*.json)")

    args = parser.parse_args()

    if args.cmd == "train":
        train(
            catalog_path = args.catalog,
            n_epochs     = args.epochs,
            batch_size   = args.batch,
            lr           = args.lr,
            hidden_dim   = args.hidden,
            n_layers     = args.layers,
            save_path    = args.save,
        )
    elif args.cmd == "probe":
        run_probe(
            catalog_path = args.catalog,
            model_path   = args.model,
            top_n        = args.top,
            hidden_dim   = args.hidden,
            n_layers     = args.layers,
        )
    elif args.cmd == "iug":
        probe_specific(
            model_path = args.model,
            hidden_dim = args.hidden,
            n_layers   = args.layers,
        )
    elif args.cmd == "entry":
        probe_entry(
            name         = args.name,
            model_path   = args.model,
            catalog_path = args.catalog,
            hidden_dim   = args.hidden,
            n_layers     = args.layers,
            no_model     = args.no_model,
        )
    elif args.cmd == "verify-recovery":
        verify_recovery(
            model_path = args.model,
            hidden_dim = args.hidden,
            n_layers   = args.layers,
        )
    elif args.cmd == "recover":
        run_probe_with_recovery(
            catalog_path = args.catalog,
            model_path   = args.model,
            top_n        = args.top,
            hidden_dim   = args.hidden,
            n_layers     = args.layers,
        )
    elif args.cmd == "stats":
        formula_stats(args.catalog)
    else:
        parser.print_help()
        print("\nQuick start:")
        print("  uv run zfc_navigator.py stats             # check formula lengths")
        print("  uv run zfc_navigator.py train             # train encoder (300 epochs)")
        print("  uv run zfc_navigator.py probe --top 30   # transmissibility map")
        print("  uv run zfc_navigator.py recover --top 30 # probe + specialist recovery")
        print("  uv run zfc_navigator.py iug               # IUG / grammar / ZFC probe")
        print("  uv run zfc_navigator.py entry <name>      # full formula + roundtrip for one entry")
        print("  uv run zfc_navigator.py entry <name> --no-model  # formula only, no model needed")
