#!/usr/bin/env python3
"""Generate gita.json — imscribed catalog for the Bhagavad Gita (18 chapters)."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def entry(num, title, desc, text, D, T, R, P, F, K, G, Gm, C, H, S, Om, tier, cscore, notes=''):
    return {'name': 'gita_%02d' % num, 'number': num, 'title': title,
            'description': desc, 'text': text,
            '\u00d0': D, '\u00de': T, '\u0158': R, '\u03a6': P,
            '\u0192': F, '\u00c7': K, '\u0393': G, '\u0262': Gm,
            '\u03c6\u0302': C, '\u0126': H, '\u03a3': S, '\u03a9': Om,
            'tier': tier, 'C_score': cscore, 'notes': notes}

Dv='\u00d0_\u03c9';Tv='\u00de_O';Rv='\u0158_=';Pv='\u03a6_}';Fv='\u0192_\u017c';Kv='\u00c7_@'
Gv='\u0393_\u0294';Gmv='\u0262_\u02cc';Cv='\u03c6\u0302_\u00ff';Hv='\u0126_!';Sv='\u03a3_\u00ef';Omv='\u03a9_z'

chapters = [
    entry(1,
        "Chapter 1: Arjuna Vishada Yoga",
        "Arjuna sees his kinsmen arrayed for battle and is overcome with grief, refusing to fight.",
        "Ranged thus for battle on the sacred plain, on Kurukshetra. Sanjaya recounts the armies. Arjuna, seeing teachers and kinsmen on both sides, is overcome: 'My members fail, my tongue dries, a shudder thrills my body. I foresee nought save woe and wail! It is not good to slay our kin!' He sinks down in his chariot, casting aside bow and arrows.",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(2,
        "Chapter 2: Sankhya Yoga",
        "Krishna teaches the immortality of the soul, the yoga of equanimity, and acting without attachment to results.",
        "Krishna: 'How hath this weakness taken thee? Cast off the coward-fit!' The wise mourn neither for the living nor the dead. Never was the spirit born, nor shall it ever cease. As one casts off worn robes and puts on new, so the spirit passes from body to body. Weapons cannot wound it, fire cannot burn it. Be equable in success and failure — this is Yoga. Let right deeds be thy motive, not their fruits.",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(3,
        "Chapter 3: Karma Yoga",
        "Krishna explains the necessity of action: no one can remain inactive; act without attachment as a sacrifice.",
        "Krishna: 'No one can remain even for a moment without doing work. Do thine allotted work, for action is superior to inaction. Work done as sacrifice must be performed; otherwise, work binds. He who controls the senses and engages in karma-yoga without attachment is distinguished. Act without attachment, constantly perform thy duty — by so doing, man reaches the Supreme.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(4,
        "Chapter 4: Jnana Karma Sannyasa Yoga",
        "Krishna reveals his divine births (avatars) through the ages and teaches action consecrated as knowledge.",
        "Krishna: 'Many births have passed for Me and thee. I know them all but thou knowest not. Whenever dharma declines, I embody Myself. For the protection of the good and destruction of evil, I am born age after age. He who knows this concerning My divine birth cometh not to birth again. Action does not stain Me. Freed from passion, fear, and anger, absorbed in Me, many have attained My being.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(5,
        "Chapter 5: Karma Sannyasa Yoga",
        "True renunciation is acting with the mind fixed on the divine, seeing the Self in all beings.",
        "Krishna: 'Both renunciation and yoga lead to the highest good, but karma-yoga is superior. The ignorant think knowledge and action are different, but the wise know they are one. He who works without attachment, offering all to Brahman, is untouched by sin as a lotus leaf by water. With the self harmonized, he sees the Self in all beings and all beings in the Self.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(6,
        "Chapter 6: Dhyana Yoga",
        "Krishna teaches the practice of meditation: the yogi seated alone, concentrated on the Self.",
        "Krishna: 'When the mind is detached from sense-objects and the self established in the Self, one has attained yoga. Let the yogi concentrate his mind on the Self, remaining in seclusion, alone, controlled, free from desires. Where the mind rests, stilled by yoga; where he sees the Self by the self — that supreme joy once attained, he never departs from truth. He who sees Me everywhere and sees all in Me, I am not lost to him.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(7,
        "Chapter 7: Jnana Vijnana Yoga",
        "Krishna reveals His higher and lower natures: all the universe is strung on Him as jewels on a thread.",
        "Krishna: 'Among thousands of men, one strives for perfection; among those, one truly knows Me. My lower nature is the eightfold division; My higher nature is the life-principle sustaining all. I am the origin and dissolution of the universe. Nothing is higher than Me. All is strung on Me as jewels on a string. I am taste in water, light in moon and sun, OM in the Vedas. I am the Self seated in the hearts of all beings.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(8,
        "Chapter 8: Akshara Brahma Yoga",
        "Who remembers Krishna at the time of death reaches Him; the imperishable Brahman and the cycle of creation.",
        "Arjuna asks: 'What is Brahman? What is the Self?' Krishna: 'Brahman is the Imperishable Supreme. Whatever state one remembers at death, that state he attains. Therefore always remember Me and fight. He who at the time of death, with unwavering mind, meditates on the Supreme Person, reaches that Supreme. With constant practice and supreme devotion, one attains the highest goal.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(9,
        "Chapter 9: Raja Vidya Raja Guhya Yoga",
        "The kingly secret: Krishna pervades yet transcends all; offered devotion however humble, He receives all.",
        "Krishna: 'Now I open to thee the deepest secret — a royal lore! By Me the whole universe is spread abroad. In Me are all existences contained, not I in them. As the air moves in space but is not space, so all things are in Me but are not I. I am the Sacrifice, the Prayer, the Father, Mother, Ancestor, Guard. Whoever offers Me with devotion a leaf, a flower, a fruit, or water — that I accept.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(10,
        "Chapter 10: Vibhuti Yoga",
        "Krishna declares His divine manifestations: He is the best of all things, the source of all splendor.",
        "Krishna: 'All that is splendid, glorious, and mighty — know it springs from a fragment of My splendor. I am the Self seated in all hearts, the beginning, middle, and end of all beings. Among lights I am the sun; among stars the moon; of Vedas the Sama-Veda; of rivers the Ganges; among warriors I am Arjuna. What need of extensive knowledge? I support the entire universe with a single fragment of Myself.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(11,
        "Chapter 11: Visvarupa Darshana Yoga",
        "Krishna reveals His cosmic form: the entire universe gathered in one body — a thousand suns, time devouring all.",
        "Arjuna: 'Show me Thy very self, the Eternal God!' Krishna gives divine sight. Sanjaya: 'If a thousand suns rose in the sky, such might be that radiance.' Arjuna: 'Lord! All is wrapped in Thee! I see all gods, all beings in Thy form. I see Thee with burning glance, lips lighted by fire, fierce as the flames of dissolution. Between Thy jaws the armies are crushed. Be merciful, Lord of Lords! Refuge of the World!'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(12,
        "Chapter 12: Bhakti Yoga",
        "Those who worship Krishna with loving faith are dearest to Him; the qualities of the true devotee described.",
        "Arjuna asks which is better: worshipping the manifest or unmanifest. Krishna: 'Those who fix their minds on Me with supreme faith — them I consider the best yogis. Greater is the difficulty of those who worship the unmanifest, for that path is hard for embodied beings. He who hates no creature, friendly and compassionate, free from egoism, equal in pain and pleasure, forgiving, self-controlled — such a devotee is dear to Me.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(13,
        "Chapter 13: Kshetra Kshetrajna Vibhaga Yoga",
        "The field (body) and the knower of the field (spirit): true knowledge is recognizing the difference between Prakriti and Purusha.",
        "Krishna: 'This body is called the field; he who knows it is the knower of the field. Know Me as the knower in all bodies. He who sees the Supreme Lord existing equally in all beings, the Imperishable among the perishable — he truly sees. Both Prakriti and Purusha are beginningless. The Supreme Spirit in the body is called the Witness, the Permitter, the Supporter.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(14,
        "Chapter 14: Gunatraya Vibhaga Yoga",
        "The three gunas — sattva, rajas, tamas — bind the soul. Krishna teaches how to transcend them to liberation.",
        "Krishna: 'Sattva binds through attachment to happiness; rajas through attachment to action; tamas through negligence and sloth. When wisdom shines through every gate, sattva prevails. When greed and restlessness arise, rajas prevails. When darkness and delusion arise, tamas prevails. He who transcends these three gunas is freed from birth, death, old age, and sorrow, and attains immortality.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(15,
        "Chapter 15: Purushottama Yoga",
        "The eternal Ashvattha tree — cut it with detachment; seek the Supreme Person beyond all change.",
        "Krishna: 'They speak of the eternal Ashvattha tree with roots above and branches below, whose leaves are the Vedas. Its true form is not perceived here. Cut this firmly-rooted tree with the axe of detachment, then seek that path from which there is no return. I am the Self dwelling in all hearts. Beyond perishable and imperishable is the Supreme Person — Purushottama — by whom all is pervaded.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(16,
        "Chapter 16: Daivasura Sampad Vibhaga Yoga",
        "The divine and demonic natures: divine qualities lead to liberation, demonic to bondage.",
        "Krishna: 'Fearlessness, purity, steadfast wisdom, charity, self-control, sacrifice, study, austerity, uprightness — these mark the divine nature. Hypocrisy, arrogance, pride, anger, harshness, ignorance — these mark the demonic. Three gates to hell destroy the self: lust, anger, and greed. Abandon these. Let scripture be your authority; knowing its injunctions, act accordingly.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(17,
        "Chapter 17: Shraddhatraya Vibhaga Yoga",
        "The threefold faith — sattvic, rajasic, tamasic — and its expression in food, sacrifice, austerity, and charity.",
        "Arjuna asks about those who sacrifice with faith but disregard scripture. Krishna: 'Faith is of three kinds, born of one's nature. Sattvic faith is fixed on the divine; rajasic on power and wealth; tamasic on ghosts and spirits. Foods, sacrifices, austerities, and charities are likewise threefold. OM TAT SAT — these three designate Brahman. With these, acts of sacrifice, austerity, and charity are rightly performed.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
    entry(18,
        "Chapter 18: Moksha Sannyasa Yoga",
        "The final synthesis: renunciation, the gunas in action, and the ultimate teaching — surrender all dharma and seek Krishna alone.",
        "Krishna: 'The wise say Sannyas is foregoing acts of desire; Tyaga is renouncing the fruits of acts. Knowledge, the known, and the knower — these three are the starting-ground of action. Fix thy mind on Me, be devoted to Me, sacrifice to Me, bow down to Me. Abandon all dharmas and take refuge in Me alone. I will liberate thee from all sins. Grieve not. Wherever Krishna and Arjuna are, there shall victory be.'",
        Dv,Tv,Rv,Pv,Fv,Kv,Gv,Gmv,Cv,Hv,Sv,Omv,'O_inf',0.94,''),
]

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gita.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(chapters, f, ensure_ascii=False, indent=2)
print("Wrote %d entries -> %s" % (len(chapters), out))
