#!/usr/bin/env python3
"""Generate tao_te_ching.json — 81-chapter Tao Te Ching catalog in IG format.
Run once: python3 gen_tao.py
Text: Legge 1891 translation (public domain).
"""
import json, os

# Field key for criticality (pre-migration name used in all catalog files)
PHI = '⊙'

def entry(num, title, desc, text, D, T, R, P, F, K, G, Gm, C, H, S, Om, tier, cscore, notes=""):
    return {
        "name": f"tao_te_ching_{num:02d}",
        "number": num,
        "title": title,
        "description": desc,
        "text": text,
        "Ð": D, "Þ": T, "Ř": R, "Φ": P, "ƒ": F,
        "Ç": K, "Γ": G, "ɢ": Gm, PHI: C,
        "Ħ": H, "Σ": S, "Ω": Om,
        "tier": tier, "C_score": cscore, "notes": notes,
    }

chapters = [
    entry(1, "Embodying the Tao",
        "The Tao that can be named is not the eternal Tao; named and unnamed coalesce.",
        "The Tao that can be trodden is not the enduring and unchanging Tao. The name that can be named is not the enduring and unchanging name.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^∧","𐑻","𐑫","𐑕","𐑭",
        "T_inf", 0.97,
        "Self-referential: the statement that names the Tao undoes itself. Named/unnamed coalesce at the EP — the exceptional point where both modes merge."),

    entry(2, "The Nourishment of the Person",
        "Beauty and ugliness, good and evil arise together as paired opposites; the sage acts without striving.",
        "When the people of the world all know beauty as beauty, there arises the recognition of ugliness. When they all know the good as good, there arises the recognition of evil.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ð","Ç^Ù","𐑲","ɢ^∧","⊙","𐑖","𐑕","𐑴",
        "T_2", 0.62,
        "Yin/yang structure of perception: each concept creates its opposite. Wu wei (Ç^Ù) as the sage's response to paired emergence."),

    entry(3, "Keeping the People at Rest",
        "Do not exalt the gifted; empty minds and fill bellies; govern through non-action.",
        "Not to value and employ men of superior ability is the way to keep the people from rivalry among themselves.",
        "𐑛","𐑶","𐑩","𐑗","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑓","𐑙","𐑷",
        "T_0", 0.18,
        "Practical governance: compact scope, direct instruction, sub-critical stability as the goal."),

    entry(4, "The Fountainless",
        "The Tao is an empty vessel, used but never filled; the primordial ancestor of all things.",
        "The Tao is like the emptiness of a vessel; and in our employment of it we must be on our guard against all fullness.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^∧","𐑻","𐑫","𐑙","𐑭",
        "T_inf", 0.95,
        "The Tao as empty fullness: holographic, self-referential, EP criticality. The vessel that pre-dates God."),

    entry(5, "The Use of Emptiness",
        "Heaven and earth are impartial; the sage is impartial; the space between heaven and earth is like a bellows.",
        "Heaven and earth do not act from any wish to be benevolent; they deal with all things as the dogs of grass are dealt with.",
        "𐑼","𐑥","𐑾","𐑯","ƒ^ż","Ç^W","𐑲","ɢ^∧","⊙","𐑖","𐑕","𐑭",
        "T_2", 0.65,
        "Pure symmetry (𐑯) encodes impartiality; lateral relational mode (𐑾) marks non-preferential stance."),

    entry(6, "The Completion of Material Forms",
        "The valley spirit never dies; it is called the mysterious female, the root of heaven and earth.",
        "The valley spirit dies not, aye the same. The female mystery thus do we name. Its gate, from which at first they issued forth, is called the root from which grew heaven and earth.",
        "𐑦","𐑸","𐑽","𐑿","ƒ^ì","Ç^@","𐑲","ɢ^Ş","⊙","𐑫","𐑙","𐑭",
        "T_3", 0.88,
        "The valley/female as generative topology: holographic, reverberant grammar (ɢ^Ş), psi polarity (𐑿 = golden-ratio generative)."),

    entry(7, "Sheathing the Light",
        "Heaven endures, earth lasts long; the sage puts himself last and is found in front.",
        "Heaven is long-enduring and earth continues long. The reason why heaven and earth are able to endure and continue thus long is because they do not live of, or for, themselves.",
        "𐑼","𐑥","𐑽","𐑹","ƒ^ð","Ç^Ù","𐑔","ɢ^ˌ","𐑢","𐑫","𐑙","𐑭",
        "T_2", 0.70,
        "Self-sacrifice as self-preservation: the Frobenius condition (𐑹) at work — putting oneself last = finding oneself first."),

    entry(8, "The Placid and Contented Nature",
        "The highest excellence is like water; it benefits all things without striving, dwelling in low places.",
        "The highest excellence is like that of water. The excellence of water appears in its benefiting all things, and in its occupying, without striving to the contrary, the low place which all men dislike.",
        "𐑛","𐑰","𐑾","𐑯","ƒ^ż","Ç^@","𐑔","ɢ^ˌ","𐑢","𐑖","𐑙","𐑭",
        "T_1", 0.45,
        "Water as structural archetype: nested topology (𐑰 = fills all spaces), symmetric polarity, sub-critical stability."),

    entry(9, "Returning to the Root",
        "To hold and fill to the brim is not as good as stopping in time; knowing when to stop is enduring.",
        "Better leave a vessel unfilled, than to attempt to carry it when it is full. If you keep feeling a point that has been sharpened, the point cannot long preserve its sharpness.",
        "𐑛","𐑶","𐑩","𐑬","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑓","𐑙","𐑷",
        "T_0", 0.20,
        "Practical bounded wisdom: the box topology marks the limit; stopping before the limit is the lesson."),

    entry(10, "Possibilities through Serenity",
        "Can you hold body and soul together in one embrace, without separation? Can you be the valley of the world?",
        "When the intelligent and animal souls are held together in one embrace, they can be kept from separating. When one gives undivided attention to the vital breath, and brings it to the utmost degree of pliancy, he can become as a tender babe.",
        "𐑨","𐑸","𐑽","𐑹","ƒ^ì","Ç^@","𐑔","ɢ^∧","⊙","𐑖","𐑙","𐑭",
        "T_2", 0.72,
        "The chapter structured as six questions — each asks whether the seeker can hold a paradox. ɢ^∧ (simultaneous) captures the and-structure."),

    entry(11, "The Use of Vacancy",
        "Thirty spokes share a hub; the wheel's usefulness lies in the empty center.",
        "The thirty spokes unite in the one nave; but it is on the empty space for the axle that the use of the wheel depends.",
        "𐑛","𐑰","𐑽","𐑹","ƒ^ż","Ç^Ù","𐑚","ɢ^∧","𐑢","𐑓","𐑕","𐑭",
        "T_1", 0.48,
        "Three parallel examples (wheel, vessel, room) all encode the same topology: the empty interior is what enables use. Frobenius self-duality: being and non-being are codependent."),

    entry(12, "The Repression of the Desires",
        "The five colors blind the eye; the five tones deafen the ear; sense excess destroys; the sage acts for the belly not the eye.",
        "Color's five hues from the eyes their sight will take; music's five notes the ears as deaf can make; the flavours five will set the mouth in pain.",
        "𐑛","𐑡","𐑩","𐑗","ƒ^ð","Ç^-","𐑲","ɢ^ˌ","𐑢","𐑓","𐑕","𐑷",
        "T_0", 0.22,
        "Network topology (𐑡) encodes the flat undifferentiated world of sense stimuli. Fast kinetics (Ç^-) for the percussive assault of sensation."),

    entry(13, "Loathing Shame",
        "Accept humiliation as a surprise; value great trouble as your own self; who values the world as his self may be trusted with it.",
        "Favour and disgrace would seem equally to be feared. Honour and great calamity are, in their nature, like the body.",
        "𐑨","𐑥","𐑾","𐑬","ƒ^ì","Ç^W","𐑔","ɢ^ˌ","⊙","𐑖","𐑙","𐑭",
        "T_2", 0.58,
        "The paradox of making the world's trouble your own — lateral relational mode because the sage doesn't dominate; bowtie where self meets world."),

    entry(14, "Manifestation of the Mystery",
        "Look and cannot see; listen and cannot hear; grasp and cannot hold — the Tao is beyond the senses, formless and unchanging.",
        "We look at it, and we do not see it, and we name it the Equable. We listen to it, and we do not hear it, and we name it the Inaudible. We try to grasp it, and do not get hold of it, and we name it the Subtle.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^∧","𐑻","𐑫","𐑙","𐑭",
        "T_inf", 0.94,
        "The three negations (invisible/inaudible/ungrasped) merge into formlessness: EP criticality, modes coalesce. One of the core metaphysical chapters."),

    entry(15, "The Exhibition of the Properties of the Tao",
        "The ancient masters were subtle, mysterious, profound, responsive — watchful like men crossing winter ice.",
        "The skilful masters of the Tao in old times, with a subtle and exquisite penetration, comprehended its mysteries, and their comprehension was too deep for others to comprehend it.",
        "𐑨","𐑰","𐑩","𐑿","ƒ^ì","Ç^@","𐑔","ɢ^∧","⊙","𐑫","𐑕","𐑭",
        "T_2", 0.75,
        "Portrait of the ancient sage: complex psi-polarity (𐑿) captures the multi-faceted enumeration; infinite chirality for the ancestral exemplars."),

    entry(16, "Returning to the Root",
        "Empty yourself of everything; let the mind become still; all things arise, act, and return to their root.",
        "The state of vacancy should be brought to the utmost degree, and that of stillness guarded with unwearying vigour. All things alike go through their processes of activity, and then we see them return to their original state.",
        "𐑼","𐑰","𐑽","𐑯","ƒ^ż","Ç^@","𐑲","ɢ^ˌ","𐑢","𐑫","𐑕","𐑭",
        "T_2", 0.68,
        "The return sequence: empty → still → arise → act → return → root → constant. Sequential grammar with infinite chirality. The great cycle."),

    entry(17, "Returning to Purity",
        "The best ruler is barely known; next loved; next feared; worst despised.",
        "In the highest antiquity, the people did not know that there were their rulers. In the next age, they loved them and praised them. In the next, they feared them.",
        "𐑛","𐑡","𐑩","𐑬","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑖","𐑕","𐑷",
        "T_0", 0.25,
        "Taxonomy of governance: four levels encoded in sequential grammar. The best ruler leaves no trace (Ç^Ù, still)."),

    entry(18, "The Decay of Manners",
        "When the great Tao is abandoned, benevolence and righteousness appear; when they appear, the Tao is already lost.",
        "When the Great Tao became neglected, benevolence and righteousness came into vogue. Then appeared wisdom and shrewdness, and there ensued great hypocrisy.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ì","Ç^W","𐑔","ɢ^ˌ","⊙","𐑖","𐑕","𐑴",
        "T_2", 0.55,
        "Each virtue that appears marks a prior loss: benevolence signals the Tao's absence. Z2 winding — the binary oscillation between authentic and counterfeit."),

    entry(19, "Returning to the Unadulterated",
        "Give up sainthood; renounce wisdom; give up benevolence; discard profit; return to simplicity, the uncarved block.",
        "If we could renounce our sageness and discard our wisdom, it would be better for the people a hundredfold.",
        "𐑛","𐑶","𐑩","𐑗","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑓","𐑙","𐑷",
        "T_0", 0.15,
        "Imperative mode: shed the accretions (𐑗 = directional asymmetry of the command). The uncarved block (p'u) as the destination."),

    entry(20, "Being Different from Ordinary Men",
        "Give up learning; put an end to troubles; the sage is unclear and alone, different from others, nourished by the mother.",
        "When we renounce learning we have no troubles. The respectful scholar and the rude rustic, how small the difference! But the good and the evil, how great is the difference!",
        "𐑨","𐑥","𐑾","𐑿","ƒ^ì","Ç^@","𐑔","ɢ^∧","⊙","𐑖","𐑙","𐑷",
        "T_2", 0.60,
        "The sage as singular: psi-polarity (𐑿) for the complex, alone identity. The most personal chapter — Laozi as the drifting outsider."),

    entry(21, "The Empty Heart, or the Tao in Its Operation",
        "The greatest virtue follows the Tao alone; the Tao is elusive yet contains images, things, essences, truth.",
        "The grandest forms of active force from Tao come, their only source. Who can of Tao the nature tell? Our sight it flies, our touch as well.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^∧","𐑮","𐑫","𐑙","𐑭",
        "T_3", 0.90,
        "The Tao contains all four strata (image, thing, essence, truth) simultaneously: c_complex criticality captures the multi-mode structure."),

    entry(22, "Increase by Humility",
        "Yield and overcome; bend and be straight; empty and be full; the sage embraces the one and becomes a model for the world.",
        "To yield is to be preserved whole. To be bent is to become straight. To be hollow is to be filled. To be tattered is to be renewed. To be in want is to possess.",
        "𐑨","𐑥","𐑽","𐑹","ƒ^ì","Ç^Ù","𐑲","ɢ^∧","⊙","𐑖","𐑕","𐑭",
        "T_2", 0.73,
        "Frobenius structure of paradox: each reversal is a self-dual identity. ɢ^∧ encodes the simultaneous assertion of all paradox-pairs."),

    entry(23, "Absolute Vacancy",
        "To talk little is natural; storms do not last; work in harmony with the Tao and success follows.",
        "Abstaining from speech marks him who is obeying the spontaneity of his nature. A violent wind does not last for a whole morning; a sudden rain does not last for the whole day.",
        "𐑛","𐑥","𐑾","𐑯","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑓","𐑙","𐑷",
        "T_0", 0.28,
        "Brevity as structural value: the short chapter enacts its own teaching. Compact scope, still kinetics, open winding."),

    entry(24, "Painful Graciousness",
        "He who stands on tiptoe does not stand firm; showing off has no merit; leftovers and waste.",
        "He who stands on his tiptoes does not stand firm; he who stretches his legs does not walk easily.",
        "𐑛","𐑡","𐑩","𐑗","ƒ^ð","Ç^-","𐑚","ɢ^ˌ","𐑣","𐑓","𐑙","𐑷",
        "T_0", 0.30,
        "Supercritical striving (𐑣) fails: the one who grows and displays will not endure. Fast kinetics for the percussive overreach."),

    entry(25, "Representations of the Mystery",
        "Something mysteriously formed before heaven and earth; alone and unchanged; mother of all things; man follows earth, earth heaven, heaven Tao, Tao nature.",
        "There was something undefined and complete, coming into existence before Heaven and Earth. How still it was and formless, standing alone, and undergoing no change, reaching everywhere and in no danger of being exhausted!",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^ˌ","𐑻","𐑫","𐑕","𐑭",
        "T_inf", 0.96,
        "The cosmological chapter: four great things in sequential hierarchy ending in nature (tzu-jan). EP criticality — all modes merge in the primordial."),

    entry(26, "The Quality of Gravity",
        "Gravity is the root of lightness; stillness is the ruler of movement; the sage never leaves his root.",
        "Gravity is the root of lightness; stillness, the ruler of movement.",
        "𐑨","𐑰","𐑩","𐑬","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑖","𐑙","𐑭",
        "T_1", 0.40,
        "Root/branch topology (𐑰): gravity contains lightness. Ç^Ù (still) as the kinetic signature of the master of unrest."),

    entry(27, "Dexterity in Using the Tao",
        "A good traveler leaves no tracks; a good speaker makes no errors; the sage abandons no one and adopts the bad as teachers of the good.",
        "The skilful traveller leaves no traces of his wheels or footsteps; the skilful speaker says nothing that can be found fault with or blamed.",
        "𐑨","𐑥","𐑾","𐑬","ƒ^ż","Ç^W","𐑔","ɢ^ˌ","𐑢","𐑖","𐑕","𐑭",
        "T_1", 0.50,
        "Paired inversions: best traveler/speaker/etc. encode the same sub-critical excellence. Bad ones are teachers of the good — relational mode is lateral."),

    entry(28, "Returning to Simplicity",
        "Know the masculine, keep to the feminine; be the valley of the world; know honor, keep humiliation; return to the uncarved block.",
        "Who knows his manhood's strength, yet still his female feebleness maintains; as to one channel flow the streams, down to him all the world complains.",
        "𐑼","𐑰","𐑽","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^ˌ","𐑢","𐑖","𐑕","𐑭",
        "T_2", 0.70,
        "Three parallel know/keep pairs (masculine/feminine, white/black, honour/humiliation) converging to the uncarved block. Frobenius self-duality."),

    entry(29, "Taking No Action",
        "Do you think you can take over the universe and improve it? The world is sacred — it cannot be improved.",
        "If any one should wish to get the kingdom for himself, and to effect this by what he does, I see that he will not succeed.",
        "𐑼","𐑥","𐑾","𐑬","ƒ^ð","Ç^Ù","𐑔","ɢ^∧","𐑢","𐑖","𐑕","𐑷",
        "T_1", 0.42,
        "The sacred nature of the world forbids intervention. Lateral relational mode: no superiority. Ç^Ù encodes non-action."),

    entry(30, "A Caveat against War",
        "Whoever relies on the Tao in governing does not force issues or defeat enemies by force; force decays quickly.",
        "Whoever relies on the Tao in governing men does not try to force issues or defeat enemies by force of arms.",
        "𐑛","𐑶","𐑾","𐑬","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑓","𐑙","𐑷",
        "T_0", 0.20,
        "Compact governance: the box topology marks the bounded domain; non-force is still (Ç^Ù)."),

    entry(31, "Stilling War",
        "Weapons are tools of violence; the sage uses them only as a last resort; victory in battle is a funeral.",
        "Now arms, however beautiful, are instruments of evil omen, hateful, it may be said, to all creatures.",
        "𐑛","𐑶","𐑩","𐑗","ƒ^ż","Ç^-","𐑚","ɢ^ˌ","𐑣","𐑓","𐑙","𐑷",
        "T_0", 0.28,
        "Supercritical (𐑣) marks the unstable, growing violence of war. Fast kinetics (Ç^-). Victory is mourning — the chapter ends in grief."),

    entry(32, "The Tao with No Name",
        "The Tao forever unnamed; the uncarved block; all would follow; know where to stop; the Tao's names arise but know their limit.",
        "The Tao, considered as unchanging, has no name. Though in its primordial simplicity it may be small, the whole world dares not deal with it as a minister.",
        "𐑦","𐑰","𐑽","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^ˌ","⊙","𐑫","𐑕","𐑭",
        "T_3", 0.82,
        "Names emerge from the unnamed Tao as rivers flow to the sea: nested topology, sequential grammar, infinite chirality."),

    entry(33, "Discriminating between the Two",
        "Knowing others is wisdom; knowing yourself is enlightenment; mastering yourself is true power.",
        "To know men is to have wisdom; to know oneself is to be enlightened. Men who overcome others are strong; he who overcomes himself is mighty.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ż","Ç^W","𐑚","ɢ^ˌ","⊙","𐑖","𐑙","𐑭",
        "T_1", 0.52,
        "Four pairs in ascending hierarchy. The chapter is a ladder: knowing → mastering; others → self. Each step through the bowtie."),

    entry(34, "The Task of Achievement",
        "The great Tao flows everywhere; it nourishes all without claiming greatness; it is great because it makes no claim to greatness.",
        "All-pervading is the Great Tao. It may be found on the left hand and on the right. All things depend on it for their production, which it gives to them, not one refusing obedience to it.",
        "𐑦","𐑸","𐑾","𐑯","ƒ^ì","Ç^@","𐑲","ɢ^Ş","⊙","𐑖","𐑕","𐑭",
        "T_2", 0.80,
        "Reverberant grammar (ɢ^Ş) for the Tao that flows everywhere without preference. Pure symmetry (𐑯) of impartial nourishment."),

    entry(35, "The Attribute of Benevolence",
        "Grasp the great Form and all the world comes to you; music and food attract passersby but the Tao is tasteless.",
        "To him who holds in his hands the Great Image of the invisible Tao, the whole world repairs.",
        "𐑦","𐑰","𐑩","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^Ş","⊙","𐑫","𐑕","𐑭",
        "T_3", 0.85,
        "The great Form as attractor: nested topology, reverberant grammar. The tasteless, invisible thing that draws the world."),

    entry(36, "Hiding the Light",
        "What you wish to shrink, first allow to expand; what you wish to take, first give; the soft overcomes the hard.",
        "When one is about to take an inspiration, he is sure to make a prior expiration; one who is going to weaken another begins by making him strong.",
        "𐑨","𐑥","𐑽","𐑹","ƒ^ì","Ç^W","𐑔","ɢ^ˌ","⊙","𐑖","𐑕","𐑴",
        "T_2", 0.62,
        "Preparatory paradox: each pair is a first-X-then-Y structure. Z2 winding captures the binary oscillation of the strategy."),

    entry(37, "The Exercise of Government",
        "The Tao does nothing yet leaves nothing undone; if princes follow it, all things transform themselves.",
        "The Tao in its regular course does nothing for the sake of doing it, and so there is nothing which it does not do.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ż","Ç^Ù","𐑲","ɢ^∧","𐑻","𐑫","𐑙","𐑭",
        "T_inf", 0.93,
        "Wu wei as the hinge of Book I. The paradox of action/non-action at the EP: modes coalesce. Frobenius self-duality of doing-nothing = doing-everything."),

    entry(38, "Discussing the Attributes of the Tao",
        "A truly good man is not aware of his goodness; the conscious virtue is not virtue; the decline from Tao produces ethics, then laws.",
        "Those who possessed in highest degree the attributes of the Tao did not seek to show them, and hence they possessed them.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ì","Ç^W","𐑲","ɢ^ˌ","⊙","𐑖","𐑕","𐑭",
        "T_2", 0.68,
        "Opens Book II. Sequential hierarchy of decline: highest virtue (unconscious) → benevolence → righteousness → propriety. Each step signals a prior loss."),

    entry(39, "The Origin of the Law",
        "These things from ancient times arose from the One: sky, earth, spirit, valley, creatures, princes — all complete through the One.",
        "The things which from of old have got the One, the Tao, are: Heaven which by it is bright and pure; Earth rendered thereby firm and sure.",
        "𐑼","𐑰","𐑩","𐑹","ƒ^ż","Ç^@","𐑲","ɢ^∧","⊙","𐑫","𐑕","𐑭",
        "T_2", 0.75,
        "The enumeration of six things holding the One: simultaneous grammar (ɢ^∧), nested topology. Noble has humble as root — Frobenius."),

    entry(40, "Returning to Non-Existence",
        "Return is the movement of the Tao; yielding is the way of the Tao; from not-being arises being.",
        "The movement of the Tao by contraries proceeds; and weakness marks the course of Tao's mighty deeds. All things under heaven sprang from It as existing; that existence sprang from It as non-existing.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ż","Ç^Ù","𐑲","ɢ^ˌ","𐑻","𐑫","𐑙","𐑭",
        "T_inf", 0.96,
        "The briefest chapter, maximum density. From not-being → being → ten thousand things. EP: the two modes (being/non-being) coalesce."),

    entry(41, "Sameness and Difference",
        "The wise student hears the Tao and practices it; the average student half-believes; the foolish student laughs — without laughter it wouldn't be the Tao.",
        "Scholars of the highest class, when they hear about the Tao, earnestly carry it into practice. Scholars of the middle class, when they have heard about it, seem now to keep it and now to lose it.",
        "𐑼","𐑡","𐑩","𐑿","ƒ^ì","Ç^W","𐑲","ɢ^ˌ","𐑮","𐑖","𐑕","𐑭",
        "T_3", 0.78,
        "Three types of students; twelve paradoxical descriptions of the Tao follow. c_complex criticality for the multi-mode, contradictory-seeming path."),

    entry(42, "The Transformations of the Tao",
        "Tao begot one; one begot two; two begot three; three begot the ten thousand things; yin and yang harmonize.",
        "The Tao produced One; One produced Two; Two produced Three; Three produced All things. All things leave behind them the Obscurity out of which they have come, and go forward to embrace the Brightness into which they have merged.",
        "𐑼","𐑰","𐑽","𐑹","ƒ^ż","Ç^@","𐑲","ɢ^ˌ","𐑣","𐑫","𐑳","𐑭",
        "T_inf", 0.91,
        "The cosmological cascade: 1→2→3→∞. Asymmetric stoichiometry (𐑳) for the n→m generation. Supercritical expansion (𐑣). The central ontological chapter."),

    entry(43, "The Universal Use of Non-Action",
        "The softest thing in the universe overcomes the hardest; non-being penetrates where there is no space; the benefit of non-action.",
        "The softest thing in the world dashes against and overcomes the hardest; that which has no substantial existence enters where there is no crevice.",
        "𐑨","𐑥","𐑽","𐑹","ƒ^ż","Ç^Ù","𐑲","ɢ^∧","⊙","𐑖","𐑙","𐑭",
        "T_2", 0.70,
        "Soft/hard polarity resolved by Frobenius: emptiness as the penetrating force. Few in the world practice this teaching."),

    entry(44, "Cautions",
        "Fame or integrity — which matters more? Money or health — which is more precious? Gain or loss — which is more harmful?",
        "Fame or self: which matters most? Your money or your life: which is more precious? Gain or loss: which is more painful?",
        "𐑨","𐑥","𐑾","𐑬","ƒ^ż","Ç^W","𐑚","ɢ^ˌ","𐑢","𐑓","𐑕","𐑷",
        "T_1", 0.38,
        "Three questions, three answers. Knowing when enough is enough is a sub-critical insight. Lateral mode: these are peer-level warnings, not commands."),

    entry(45, "Great Seeming Imperfect",
        "True perfection seems imperfect yet it is perfectly itself; true fullness seems empty; stillness overcomes heat; quiet overcomes noise.",
        "Who thinks his great achievements poor shall find his vigour long endure. The greatest cleverness seems like stupidity; the greatest eloquence seems like stuttering.",
        "𐑨","𐑥","𐑽","𐑹","ƒ^ì","Ç^Ù","𐑔","ɢ^∧","⊙","𐑖","𐑕","𐑭",
        "T_2", 0.65,
        "Five paradoxes of greatness: each great thing appears as its opposite. Frobenius self-duality holds them together."),

    entry(46, "The Moderating of Desire",
        "When the Tao prevails, horses haul manure; when it is abandoned, war horses breed on the frontier; greatest sin is desire.",
        "When the Tao prevails in the world, they send back their swift horses to draw dung-carts. When the Tao is disregarded in the world, war-horses have to be reared even on the starvation-fields.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ð","Ç^W","𐑔","ɢ^ˌ","⊙","𐑖","𐑙","𐑴",
        "T_2", 0.55,
        "Z2 winding: binary oscillation between Tao-present and Tao-absent world states. The horses are the diagnostic."),

    entry(47, "Surveying What Is Far-off",
        "Without going outside you may know the whole world; without looking through the window you may see the Tao of heaven.",
        "Without going outside his door, one understands all that takes place under the sky; without looking out from his window, one sees the Tao of Heaven.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ż","Ç^Ù","𐑲","ɢ^∧","𐑻","𐑖","𐑙","𐑭",
        "T_inf", 0.90,
        "The holographic principle of knowing: the inner contains the outer. EP criticality — the outside and inside coalesce. Still kinetics (Ç^Ù) for the sage who doesn't move."),

    entry(48, "Forgetting Knowledge",
        "In pursuit of learning, every day something is acquired; in pursuit of Tao, every day something is dropped.",
        "He who devotes himself to learning seeks every day to increase his knowledge; he who devotes himself to the Tao seeks every day to diminish his doing.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ż","Ç^Ù","𐑔","ɢ^ˌ","𐑻","𐑖","𐑙","𐑭",
        "T_2", 0.72,
        "The subtraction path: learning adds, Tao subtracts. EP at the limit of subtraction: non-action, nothing undone. Sequential grammar traces the path."),

    entry(49, "The Quality of Indulgence",
        "The sage has no fixed mind; he makes the mind of the people his mind; good and bad are treated with equal goodness.",
        "The sage has no invariable mind of his own; he makes the mind of the people his mind. To those who are good I act with goodness; to those who are not good I also act with goodness.",
        "𐑼","𐑥","𐑾","𐑯","ƒ^ż","Ç^@","𐑲","ɢ^∧","𐑢","𐑖","𐑕","𐑭",
        "T_2", 0.65,
        "Pure symmetry (𐑯) of impartiality: all treated equally. Lateral relational mode. The sage merges with the people."),

    entry(50, "The Value Set on Life",
        "Between birth and death three in ten are followers of life; three in ten are followers of death; the one who protects life well is untouched by harm.",
        "Man comes forth and is born; he goes back and dies. Of every ten, three are followers of life; three are followers of death; and three value their life yet in their acts they are hastening to the region of death.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ì","Ç^W","𐑔","ɢ^ˌ","⊙","𐑖","𐑕","𐑭",
        "T_2", 0.58,
        "The three-in-ten taxonomy of life-paths. The one protected by the Tao is untouched by tiger's claws or soldier's sword."),

    entry(51, "The Operation of the Mystery",
        "Every being is an expression of the Tao; Tao gives birth, virtue nourishes, substance shapes, environment completes.",
        "All things are produced by the Tao, and nourished by its outflowing operation. They receive their forms according to the nature of each, and are completed according to the circumstances of their condition.",
        "𐑼","𐑰","𐑩","𐑯","ƒ^ż","Ç^@","𐑲","ɢ^ˌ","⊙","𐑫","𐑕","𐑭",
        "T_2", 0.70,
        "Four-stage production cascade (Tao→virtue→substance→environment) in sequential grammar. The Tao nourishes without possessing."),

    entry(52, "Returning to the Source",
        "In the beginning was the Tao; all things issue from it; all return; know the children, know the mother; stop the senses and be inexhaustible.",
        "The Tao, which originated all under the sky, is to be considered as the mother of them all. When the mother is found, we know what her children should be.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ì","Ç^@","𐑲","ɢ^ˌ","⊙","𐑫","𐑕","𐑭",
        "T_3", 0.83,
        "Mother/children: knowing the mother is the return. Closing the senses is Ç^@ (slow bloom of restraint). The sealed gate (Ç^Ù) versus the open gate."),

    entry(53, "Increase of Evidence",
        "The great Way is easy yet people prefer side paths; wisdom is ostentatious; rulers eat while the fields go to ruin.",
        "If I were suddenly to become known, and to conduct a government according to the Great Tao, what I should be most afraid of would be a boastful display.",
        "𐑨","𐑡","𐑩","𐑗","ƒ^ð","Ç^W","𐑔","ɢ^ˌ","𐑣","𐑖","𐑙","𐑷",
        "T_1", 0.38,
        "Supercritical excess (𐑣) in the corrupt court: the rulers grow rich while the fields empty. The great Way abandoned for the network of side paths (𐑡)."),

    entry(54, "The Cultivation of the Tao and Its Attribute",
        "What is firmly planted cannot be uprooted; cultivate the Tao in the self, family, village, state, and world.",
        "What Tao's skilful planter plants can never be uptorn; what his skilful craftsman binds can never be undone.",
        "𐑼","𐑰","𐑩","𐑯","ƒ^ż","Ç^@","𐑲","ɢ^ˌ","𐑢","𐑫","𐑕","𐑭",
        "T_2", 0.68,
        "Hierarchical nesting: self→family→village→state→world. Each level is a stable foundation. The root that cannot be uprooted."),

    entry(55, "The Mystic Virtue",
        "One filled with the Tao is like a newborn child: insects don't sting, bones soft yet grip firm; does not yet know the union of male and female, yet perfect.",
        "He who has in himself abundantly the attributes of the Tao is like an infant. Poisonous insects will not sting him; fierce beasts will not seize him; birds of prey will not strike him.",
        "𐑛","𐑰","𐑾","𐑹","ƒ^ż","Ç^@","𐑔","ɢ^∧","⊙","𐑓","𐑙","𐑭",
        "T_1", 0.52,
        "The infant as the image of perfect virtue: Frobenius self-duality (all without asserting any). H_0 chirality — the infant has no history, only presence."),

    entry(56, "Mysterious Excellence",
        "Those who know do not talk; those who talk do not know; the sage closes mouth, blunts sharpness, merges with the dust.",
        "He who knows does not speak; he who speaks does not know. He shuts his mouth, he closes his gates, he blunts his sharp points.",
        "𐑼","𐑥","𐑽","𐑯","ƒ^ì","Ç^Ù","𐑲","ɢ^∧","𐑻","𐑖","𐑙","𐑭",
        "T_inf", 0.88,
        "Sealed mouth = sealed gate = sealed senses. EP at the merger with dust: inside and outside coalesce. The know-er cannot be benefited or harmed — above distinction."),

    entry(57, "The Genuine Influence",
        "Rule a nation with justice; wage war with surprise; win the world through non-interference; the more prohibitions the poorer the people.",
        "A state may be ruled by measures of correction; weapons of war may be used with crafty dexterity; but the kingdom is made one's own only by freedom from action and purpose.",
        "𐑛","𐑶","𐑩","𐑬","ƒ^ż","Ç^Ù","𐑔","ɢ^ˌ","𐑢","𐑖","𐑙","𐑷",
        "T_0", 0.30,
        "Three modes of governance: justice, war, non-interference. The sequential grammar traces the hierarchy, ending in wu wei."),

    entry(58, "Transformation According to Circumstances",
        "When the country is ruled with a light hand the people are simple; when ruled with a firm hand they are cunning; good and evil cycle.",
        "The government that seems the most unwise, oft goodness to the people best supplies; that which is meddling, touching everything, will work but ill, and disappointment bring.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ð","Ç^W","𐑔","ɢ^ˌ","⊙","𐑖","𐑙","𐑴",
        "T_2", 0.58,
        "Z2 winding: the cycle of good becoming evil and vice versa. The chapter's most striking line: no one knows when the cycle will end."),

    entry(59, "Guarding the Tao",
        "In caring for others and serving heaven there is nothing like restraint; restraint means storing up virtue; no limit to it.",
        "In caring for others and serving Heaven, there is nothing like using restraint.",
        "𐑛","𐑶","𐑩","𐑯","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑖","𐑙","𐑭",
        "T_0", 0.32,
        "Restraint as the accumulation of virtue: the box topology of containment. The roots go deep, the tree endures."),

    entry(60, "Occupying One's Proper Place",
        "Governing a large country is like frying a small fish; the Tao and the sage together do not harm.",
        "Governing a great state is like cooking small fish.",
        "𐑛","𐑶","𐑾","𐑯","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑓","𐑙","𐑷",
        "T_0", 0.18,
        "The simplest governance principle: minimum intervention. The smallest chapter among the governance chapters."),

    entry(61, "The Attribute of Humility",
        "A great nation is like the low land to which all streams flow; the female wins by lying still and being low.",
        "What makes a great state is its being like a low-lying, down-flowing stream; it becomes the centre to which tend all the small states under heaven.",
        "𐑨","𐑰","𐑾","𐑯","ƒ^ż","Ç^Ù","𐑔","ɢ^ˌ","𐑢","𐑖","𐑕","𐑭",
        "T_1", 0.45,
        "The downstream metaphor: nested topology (𐑰) as all streams flow to the low center. The female wins by stillness (Ç^Ù)."),

    entry(62, "Practising the Tao",
        "The Tao is the source of all things, the good man's treasure and the bad man's refuge; it is the greatest gift.",
        "Tao has of all things the most honoured place. No treasures give good men so much delight; and bad men's exile and their death are overcome by Tao.",
        "𐑦","𐑸","𐑾","𐑯","ƒ^ż","Ç^@","𐑲","ɢ^∧","⊙","𐑫","𐑕","𐑭",
        "T_2", 0.78,
        "The Tao as universal refuge: even the bad are not abandoned. Symmetric polarity (𐑯) for the universal, impartial shelter."),

    entry(63, "Thinking in the Beginning",
        "Practice non-action; work without doing; taste without tasting; repay injury with Tao; address the large while it is still small.",
        "It is the way of the Tao to act without thinking of acting; to conduct affairs without feeling the trouble of them; to taste without discerning any flavour.",
        "𐑼","𐑥","𐑽","𐑹","ƒ^ì","Ç^Ù","𐑲","ɢ^ˌ","𐑢","𐑖","𐑙","𐑭",
        "T_2", 0.68,
        "The strategy of the small: address difficulty before it becomes difficulty. The Frobenius condition: act/not-act, taste/not-taste are self-dual."),

    entry(64, "Guarding the Minute",
        "Peace is easily maintained; trouble is easily overcome when still small; the journey of a thousand miles begins with a single step.",
        "That which is at rest is easily kept hold of; before a thing has given indications of its nature, it is easy to take measures about it.",
        "𐑛","𐑶","𐑩","𐑬","ƒ^ż","Ç^@","𐑔","ɢ^ˌ","𐑢","𐑖","𐑙","𐑭",
        "T_1", 0.42,
        "The most famous practical aphorism: the thousand-mile journey. Sequential grammar traces action in the early stage as the key."),

    entry(65, "Pure Simplicity",
        "The ancient rulers did not try to enlighten the people; they kept them simple; governing with cleverness leads the state astray.",
        "The ancients who showed their skill in practising the Tao did so, not to enlighten the people, but rather to make them simple and ignorant.",
        "𐑨","𐑥","𐑩","𐑬","ƒ^ì","Ç^Ù","𐑔","ɢ^ˌ","𐑢","𐑖","𐑙","𐑭",
        "T_1", 0.40,
        "Simplicity versus cleverness as governance poles. Sub-critical stability is the goal. Historical depth (𐑖) for the ancient contrast."),

    entry(66, "Putting One's Self Last",
        "Why is the sea the king of a hundred streams? Because it lies below them all; the sage must be below the people.",
        "That whereby the rivers and seas are able to receive the homage and tribute of all the valley streams, is their skill in being lower than they.",
        "𐑨","𐑰","𐑾","𐑯","ƒ^ż","Ç^Ù","𐑔","ɢ^ˌ","𐑢","𐑖","𐑕","𐑭",
        "T_1", 0.42,
        "The sea metaphor: nested topology, hundred streams flowing to the lowest point. Non-competition as the path to leadership."),

    entry(67, "Three Precious Things",
        "My three treasures: compassion, frugality, and humility; from compassion comes courage; from frugality comes generosity.",
        "All the world says that, while my Tao is great, it yet appears to be inferior to other systems of teaching. Now it is just its greatness that makes it seem to be inferior.",
        "𐑛","𐑰","𐑩","𐑿","ƒ^ż","Ç^@","𐑔","ɢ^ˌ","𐑢","𐑖","𐑕","𐑭",
        "T_1", 0.48,
        "Three treasures as a nested set: each one generates the next virtue. Psi-polarity (𐑿) for the precious, complex multi-faceted teaching."),

    entry(68, "Matching Heaven",
        "The best soldier is not soldierly; the best fighter is not ferocious; the best victor wins without striving — this is the virtue of non-competition.",
        "He who in Tao's wars has skill achieves his purpose without violence; and he who in his fighting best subdues his foe combines in his action grace and self-control.",
        "𐑛","𐑥","𐑽","𐑬","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑓","𐑕","𐑷",
        "T_0", 0.25,
        "Three parallel inversions of martial expectation. The non-competitive virtue matches heaven. Compact, focused, sub-critical."),

    entry(69, "The Use of the Mysterious",
        "A master of war dares not make the first move; rather play the guest than the host; advance without moving forward.",
        "A master of the art of war has said, I do not dare to be the host of the conflict; I prefer to be the guest.",
        "𐑛","𐑶","𐑽","𐑬","ƒ^ð","Ç^Ù","𐑚","ɢ^ˌ","⊙","𐑓","𐑙","𐑷",
        "T_0", 0.28,
        "The strategy of retreat: rolling up the sleeve without showing the arm. The greatest disaster is underestimating the enemy."),

    entry(70, "The Difficulty of Being Rightly Known",
        "My teaching is easy to understand and easy to practice, yet no one in the world understands or practices it; the sage wears coarse cloth but carries jade.",
        "My words are very easy to know, and very easy to practise; but there is no one in the world who is able to know and able to practise them.",
        "𐑨","𐑥","𐑩","𐑿","ƒ^ì","Ç^W","𐑚","ɢ^ˌ","⊙","𐑖","𐑙","𐑭",
        "T_2", 0.55,
        "The hidden jade: psi-polarity for the concealed value. Easy/unknown paradox. The sage's solitude in understanding."),

    entry(71, "The Disease of Knowing",
        "Knowing ignorance is strength; ignoring knowledge is sickness; the sage recognizes his own disease and is therefore not diseased.",
        "To know and yet think we do not know is the highest attainment; not to know, and yet think we do know, is a disease.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ì","Ç^W","𐑚","ɢ^ˌ","⊙","𐑓","𐑙","𐑷",
        "T_1", 0.42,
        "The paradox of meta-cognition: knowing-that-you-don't-know is strength. The sage diagnoses the disease and is thereby healed."),

    entry(72, "Loving One's Self",
        "When people do not fear the great, disaster comes; do not oppress their dwellings; do not interfere with their lives.",
        "When the people do not fear what they ought to fear, that which is their great dread will come on them.",
        "𐑛","𐑶","𐑩","𐑬","ƒ^ð","Ç^Ù","𐑔","ɢ^ˌ","⊙","𐑖","𐑙","𐑷",
        "T_1", 0.38,
        "The sage knows himself without displaying himself, loves himself without exalting himself. Non-interference as the political wisdom."),

    entry(73, "Allowing People to Take Their Course",
        "Daring to act brings death; daring not to act preserves life; the net of heaven is vast — it catches everything.",
        "He whose boldness appears in his daring to do wrong, in consequence meets with death; he whose boldness appears in his not daring to do wrong lives on.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ð","Ç^W","𐑲","ɢ^ˌ","⊙","𐑖","𐑙","𐑭",
        "T_2", 0.58,
        "Bowtie topology where bold action and bold restraint cross: one leads to death, the other to life. The vast net of heaven catches without striving."),

    entry(74, "Restraining Delusion",
        "If men do not fear death, what is the use of threatening them with it? The executioner is heaven; usurping that role brings harm.",
        "When the people do not fear death, to what purpose is it to try to frighten them with death?",
        "𐑛","𐑶","𐑩","𐑬","ƒ^ð","Ç^-","𐑚","ɢ^ˌ","𐑣","𐑓","𐑙","𐑷",
        "T_0", 0.25,
        "Supercritical (𐑣) marks the unstable overreach of the ruler who usurps heaven's role. Fast kinetics for the sudden violence of execution."),

    entry(75, "How Greediness Injures",
        "When taxes are too high the people go hungry; when rulers interfere too much the people rebel; valuing life too much makes death come easily.",
        "When the people are hungry, it is because those in authority eat up too much of the tax-grain.",
        "𐑛","𐑡","𐑩","𐑗","ƒ^ð","Ç^W","𐑔","ɢ^ˌ","𐑣","𐑓","𐑙","𐑷",
        "T_0", 0.28,
        "Supercritical excess (𐑣) of the extractive state. Network topology (𐑡) for the tax network. Asymmetric polarity (𐑗) of unilateral extraction."),

    entry(76, "A Warning against Trusting in Strength",
        "A man is born gentle and weak; at death he is hard and stiff; living things are soft and yielding; dead things are hard and stiff.",
        "Man at his birth is supple and weak; at his death, firm and strong. So it is with all things. Trees and plants, in their early growth, are soft and supple.",
        "𐑨","𐑥","𐑽","𐑬","ƒ^ż","Ç^W","𐑔","ɢ^ˌ","⊙","𐑖","𐑙","𐑭",
        "T_2", 0.58,
        "The life/death polarity encoded as soft/hard. The hard and strong belong to death; the soft and yielding belong to life. Sequential lesson from observation."),

    entry(77, "The Way of Heaven",
        "The Tao is like the bending of a bow — the high end is brought down, the low is raised; it takes from excess and gives to deficiency.",
        "May not the way of Heaven be compared to the method of bending a bow? The part of the bow which was high is brought low, and what was low is raised up.",
        "𐑼","𐑥","𐑽","𐑯","ƒ^ż","Ç^@","𐑲","ɢ^ˌ","⊙","𐑖","𐑕","𐑭",
        "T_2", 0.68,
        "The bow as the image of heaven's redistribution: high brought low, low raised. Pure symmetry (𐑯) of the balanced tension. The sage gives without accumulating."),

    entry(78, "Confidence in Faith",
        "Under heaven nothing is more soft and yielding than water yet for attacking the hard there is nothing that surpasses it.",
        "There is nothing in the world more soft and weak than water, and yet for attacking things that are firm and strong there is nothing that can take precedence of it.",
        "𐑨","𐑥","𐑽","𐑹","ƒ^ż","Ç^@","𐑲","ɢ^∧","⊙","𐑖","𐑙","𐑭",
        "T_2", 0.73,
        "Water as Frobenius archetype: contains all without claiming any. The ruler who bears the curse of the state bears the kingdom. The paradox that everyone knows but nobody practices."),

    entry(79, "Adherence to One's Contracts",
        "After a bitter quarrel some resentment remains; the sage keeps his half of the contract without demanding the other's.",
        "When a reconciliation is effected after a great animosity, there is sure to be a grudge remaining.",
        "𐑨","𐑥","𐑾","𐑬","ƒ^ð","Ç^W","𐑔","ɢ^ˌ","⊙","𐑖","𐑙","𐑭",
        "T_1", 0.48,
        "The sage holds the left tally without enforcing it. Heaven is always with the good — no favorites. Lateral relational mode: no compulsion."),

    entry(80, "Standing Alone",
        "A small country with few people; enough tools but not used; people value life and don't wander; neighbors in sight but not visited.",
        "In a little state with a small population, I would so order it, that though there were individuals with the abilities of ten or a hundred men, there should be no employment of them.",
        "𐑛","𐑶","𐑾","𐑯","ƒ^ż","Ç^Ù","𐑚","ɢ^ˌ","𐑢","𐑖","𐑙","𐑭",
        "T_0", 0.35,
        "The utopian small state: complete containment (𐑶), stillness (Ç^Ù), symmetric peace (𐑯). Boats and carts unused; weapons in storage. The ideal is sub-critical stability."),

    entry(81, "The Author's Ambition",
        "True words are not beautiful; beautiful words are not true; the sage does not hoard; acting without competing, the Way benefits without harming.",
        "Sincere words are not fine; fine words are not sincere. Those who are skilled in the Tao do not dispute about it; the disputatious are not skilled in it.",
        "𐑦","𐑸","𐑽","𐑹","ƒ^ż","Ç^Ù","𐑲","ɢ^∧","𐑻","𐑫","𐑕","𐑭",
        "T_inf", 0.97,
        "Final synthesis: mirrors Chapter 1 at higher resolution. EP criticality — all the paradoxes (true/beautiful, skilled/disputatious, sage/hoarder) coalesce. The loop closes."),
]

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tao_te_ching.json')
with open(out, 'w', encoding='utf-8') as f:
    json.dump(chapters, f, ensure_ascii=False, indent=2)
print(f"Wrote {len(chapters)} chapters → {out}")
