#!/usr/bin/env python3
"""Generate canonical Clay-problem Imscription tuples for the Lean tree,
sourced procedurally from IG_catalog.json (never hand-imscribed).

Inverts the per-primitive `.shavian` maps in
p4ramill/Imscribing/Primitives/Imscription.lean to turn each catalog Shavian
glyph into its Lean constructor, and emits
p4ramill/Imscribing/Millennium/ClayCanonicalTuples.lean.
"""
import json
from pathlib import Path

CATALOG = Path("/home/mrnob0dy666/imsgct/imscribing_grammar/IG_catalog.json")
OUT = Path("/home/mrnob0dy666/imsgct/p4rakernel/p4ramill/Imscribing/Millennium/ClayCanonicalTuples.lean")

# catalog label -> (Lean field, {glyph: constructor}) — inverse of the .shavian maps.
GLYPH = {
    "⊢": ("dim",  {"𐑛":"dead","𐑨":"ash","𐑼":"array","𐑦":"if'"}),
    "⊣": ("top",  {"𐑡":"judge","𐑰":"eat","𐑥":"mime","𐑶":"oil","𐑸":"are"}),
    "≻": ("rel",  {"𐑩":"ado","𐑑":"tot","𐑽":"ear","𐑾":"ian"}),
    "≺": ("pol",  {"𐑗":"church","𐑿":"yew","𐑬":"out","𐑯":"nun","𐑹":"or'"}),
    "⋈": ("fid",  {"𐑱":"age","𐑞":"they","𐑐":"peep"}),
    "⊤": ("kin",  {"𐑘":"yea","𐑤":"loll","𐑧":"egg","𐑪":"on","𐑺":"air"}),
    "∈": ("gran", {"𐑚":"bib","𐑔":"thigh","𐑲":"ice"}),
    "∋": ("gram", {"𐑝":"vow","𐑜":"gag","𐑠":"measure","𐑵":"ooze"}),
    "⊙": ("crit", {"𐑢":"woe","⊙":"monad","𐑮":"roar","𐑻":"err","𐑣":"haha"}),
    "⊥": ("chir", {"𐑓":"fee","𐑒":"kick","𐑖":"sure","𐑫":"wool"}),
    "⊞": ("stoi", {"𐑙":"hung","𐑕":"so","𐑳":"up"}),
    "◻": ("prot", {"𐑷":"awe","𐑴":"oak","𐑭":"ah","𐑟":"zoo"}),
}
FIELD_ORDER = ["dim","top","rel","pol","fid","kin","gran","gram","crit","chir","stoi","prot"]
# canonical catalog entry name -> Lean def name
TARGETS = {
    "yang_mills_mass_gap":   "yangMillsMassGap",
    "birch_swinnerton_dyer": "birchSwinnertonDyer",
    "hodge_conjecture":      "hodgeConjecture",
    "riemann_hypothesis":    "riemannHypothesis",
    "navier_stokes":         "navierStokes",
    "p_vs_np":               "pVsNP",
}

def load_entries():
    c = json.loads(CATALOG.read_text(encoding="utf-8"))
    ents = c if isinstance(c, list) else (list(c.values()) if isinstance(c, dict) else [])
    return {e["name"]: e for e in ents if isinstance(e, dict) and "name" in e}

def to_lean(entry):
    fields = {}
    for label, (field, gmap) in GLYPH.items():
        glyph = entry[label]
        if glyph not in gmap:
            raise ValueError(f"glyph {glyph!r} for {label} not in map (entry {entry['name']})")
        fields[field] = gmap[glyph]
    return ", ".join(f"{f} := .{fields[f]}" for f in FIELD_ORDER)

def main():
    ents = load_entries()
    lines = [
        "import Imscribing.Primitives.Imscription",
        "",
        "/-!",
        "# ClayCanonicalTuples — Clay-problem imscriptions sourced from IG_catalog.json",
        "",
        "GENERATED by scripts/gen_clay_canonical_tuples.py — do not edit by hand.",
        "Each tuple is the canonical catalog entry, decoded glyph→constructor via the",
        "inverse of the per-primitive `.shavian` maps. Regenerate after catalog changes.",
        "-/",
        "",
        "namespace Imscribing.Millennium.ClayCanonicalTuples",
        "open Imscribing.Primitives",
        "open Dimensionality Topology Relational Polarity Fidelity KineticChar",
        "     Granularity Grammar Criticality Chirality Stoichiometry Protection",
        "",
    ]
    for cat_name, lean_name in TARGETS.items():
        if cat_name not in ents:
            raise SystemExit(f"catalog missing entry: {cat_name}")
        body = to_lean(ents[cat_name])
        lines.append(f"/-- Catalog `{cat_name}`, procedurally sourced. -/")
        lines.append(f"def {lean_name} : Imscription := {{ {body} }}")
        lines.append("")
    lines.append("end Imscribing.Millennium.ClayCanonicalTuples")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    for cat_name, lean_name in TARGETS.items():
        print(f"  {lean_name}: {to_lean(ents[cat_name])}")

if __name__ == "__main__":
    main()
