#!/usr/bin/env python3
"""Generate a Lean faithfulness guard: each UniverseRulesets.ordinalX must equal
the canonical rank from imscrbgrmr/canonical_primitives.py (ORDINALS).

Bakes the authoritative canonical ranks (as exact ℚ) into `native_decide`
theorems. If any Lean ordinal function drifts from canonical, the generated
theorem fails to build — the ⊙-scale discrepancy class can never silently return.

GENERATED FILE: p4ramill/Imscribing/Millennium/CanonicalOrdinalFaithfulness.lean
Regenerate only when the canonical ORDINALS table itself changes.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path("/home/mrnob0dy666/imsgct/imscribing_grammar")))
from imscrbgrmr.canonical_primitives import ORDINALS

OUT = Path("/home/mrnob0dy666/imsgct/p4rakernel/p4ramill/Imscribing/Millennium/CanonicalOrdinalFaithfulness.lean")

# canonical label -> (Lean ordinal fn, Lean type, {glyph: constructor})
PRIM = {
    "⊢": ("ordinalD",    "Dimensionality", {"𐑛":"dead","𐑨":"ash","𐑼":"array","𐑦":"if'"}),
    "⊣": ("ordinalT",    "Topology",       {"𐑡":"judge","𐑰":"eat","𐑥":"mime","𐑶":"oil","𐑸":"are"}),
    "≻": ("ordinalR",    "Relational",     {"𐑩":"ado","𐑑":"tot","𐑽":"ear","𐑾":"ian"}),
    "≺": ("ordinalP",    "Polarity",       {"𐑗":"church","𐑿":"yew","𐑬":"out","𐑯":"nun","𐑹":"or'"}),
    "⋈": ("ordinalF",    "Fidelity",       {"𐑱":"age","𐑞":"they","𐑐":"peep"}),
    "⊤": ("ordinalK",    "KineticChar",    {"𐑘":"yea","𐑤":"loll","𐑧":"egg","𐑪":"on","𐑺":"air"}),
    "∈": ("ordinalGran", "Granularity",    {"𐑚":"bib","𐑔":"thigh","𐑲":"ice"}),
    "∋": ("ordinalG",    "Grammar",        {"𐑝":"vow","𐑜":"gag","𐑠":"measure","𐑵":"ooze"}),
    "⊙": ("ordinalPhi",  "Criticality",    {"𐑢":"woe","⊙":"monad","𐑮":"roar","𐑻":"err","𐑣":"haha"}),
    "⊥": ("ordinalH",    "Chirality",      {"𐑓":"fee","𐑒":"kick","𐑖":"sure","𐑫":"wool"}),
    "⊞": ("ordinalS",    "Stoichiometry",  {"𐑙":"hung","𐑕":"so","𐑳":"up"}),
    "◻": ("ordinalOmega","Protection",     {"𐑷":"awe","𐑴":"oak","𐑭":"ah","𐑟":"zoo"}),
}
# Exact ℚ for the canonical non-integer transitional ranks.
FRAC = {2.33: "7/3", 2.67: "8/3", 4.5: "9/2"}

def rank_to_lean(r):
    if isinstance(r, int) or float(r).is_integer():
        return str(int(r))
    if r in FRAC:
        return FRAC[r]
    raise ValueError(f"no exact ℚ mapping for canonical rank {r!r}")

def main():
    lines = [
        "import Imscribing.Millennium.UniverseRulesets",
        "",
        "/-!",
        "# CanonicalOrdinalFaithfulness — ordinalX ≡ canonical ranks (machine-checked guard)",
        "",
        "GENERATED by scripts/gen_ordinal_faithfulness.py from",
        "`imscrbgrmr/canonical_primitives.py` (ORDINALS). Each theorem pins a Lean",
        "ordinal function to the authoritative canonical rank for every value. If any",
        "`ordinalX` in `UniverseRulesets` drifts from canonical, its theorem fails to",
        "build. Regenerate only when the canonical ORDINALS table itself changes.",
        "-/",
        "",
        "namespace Imscribing.Millennium.CanonicalOrdinalFaithfulness",
        "open Imscribing.Primitives Millennium.UniverseRulesets",
        "",
    ]
    thm_names = []
    for label, (fn, ty, gmap) in PRIM.items():
        table = ORDINALS[label]
        conj = []
        for glyph, ctor in gmap.items():
            rank = rank_to_lean(table[glyph])
            conj.append(f"{fn} {ty}.{ctor} = {rank}")
        name = f"{fn}_faithful"
        thm_names.append(name)
        body = " ∧\n    ".join(conj)
        lines.append(f"/-- `{fn}` matches canonical ranks for `{label}` ({len(gmap)} values). -/")
        lines.append(f"theorem {name} :\n    {body} := by native_decide")
        lines.append("")
    lines.append(f"-- {len(thm_names)} guards: "
                 + ", ".join(thm_names))
    lines.append("")
    lines.append("end Imscribing.Millennium.CanonicalOrdinalFaithfulness")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(thm_names)} faithfulness theorems)")

if __name__ == "__main__":
    main()
